package android.support.v4.media; class TransportController { void a() { int a;
a=0;// .class public abstract Landroid/support/v4/media/TransportController;
a=0;// .super Ljava/lang/Object;
a=0;// .source "TransportController.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/media/TransportController;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract getBufferPercentage()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCurrentPosition()J
a=0;// .end method
a=0;// 
a=0;// .method public abstract getDuration()J
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTransportControlFlags()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract isPlaying()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract pausePlaying()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract registerStateListener(Landroid/support/v4/media/TransportStateListener;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract seekTo(J)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract startPlaying()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract stopPlaying()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract unregisterStateListener(Landroid/support/v4/media/TransportStateListener;)V
a=0;// .end method
}}
