package android.support.v4.widget; class EdgeEffectCompat$EdgeEffectIcsImpl { void a() { int a;
a=0;// .class Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectIcsImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "EdgeEffectCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/widget/EdgeEffectCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "EdgeEffectIcsImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 90
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectIcsImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public draw(Ljava/lang/Object;Landroid/graphics/Canvas;)Z
a=0;//     .locals 1
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;//     .param p2, "canvas"    # Landroid/graphics/Canvas;
a=0;// 
a=0;//     .prologue
a=0;//     .line 120
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->draw(Ljava/lang/Object;Landroid/graphics/Canvas;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public finish(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->finish(Ljava/lang/Object;)V
a=0;// 
a=0;//     .line 105
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public isFinished(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 100
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->isFinished(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public newEdgeEffect(Landroid/content/Context;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->newEdgeEffect(Landroid/content/Context;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public onAbsorb(Ljava/lang/Object;I)Z
a=0;//     .locals 1
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;//     .param p2, "velocity"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->onAbsorb(Ljava/lang/Object;I)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onPull(Ljava/lang/Object;F)Z
a=0;//     .locals 1
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;//     .param p2, "deltaDistance"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->onPull(Ljava/lang/Object;F)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onRelease(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->onRelease(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setSize(Ljava/lang/Object;II)V
a=0;//     .locals 0
a=0;//     .param p1, "edgeEffect"    # Ljava/lang/Object;
a=0;//     .param p2, "width"    # I
a=0;//     .param p3, "height"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     invoke-static {p1, p2, p3}, Landroid/support/v4/widget/EdgeEffectCompatIcs;->setSize(Ljava/lang/Object;II)V
a=0;// 
a=0;//     .line 97
a=0;//     return-void
a=0;// .end method
}}
