package android.support.v4.widget; class ScrollerCompat$ScrollerCompatImplGingerbread { void a() { int a;
a=0;// .class Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImplGingerbread;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ScrollerCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/widget/ScrollerCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "ScrollerCompatImplGingerbread"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 150
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImplGingerbread;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abortAnimation(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 208
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->abortAnimation(Ljava/lang/Object;)V
a=0;// 
a=0;//     .line 209
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public computeScrollOffset(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 178
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->computeScrollOffset(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public createScroller(Landroid/content/Context;Landroid/view/animation/Interpolator;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "interpolator"    # Landroid/view/animation/Interpolator;
a=0;// 
a=0;//     .prologue
a=0;//     .line 153
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->createScroller(Landroid/content/Context;Landroid/view/animation/Interpolator;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public fling(Ljava/lang/Object;IIIIIIII)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;//     .param p2, "startX"    # I
a=0;//     .param p3, "startY"    # I
a=0;//     .param p4, "velX"    # I
a=0;//     .param p5, "velY"    # I
a=0;//     .param p6, "minX"    # I
a=0;//     .param p7, "maxX"    # I
a=0;//     .param p8, "minY"    # I
a=0;//     .param p9, "maxY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 195
a=0;//     invoke-static/range {p1 .. p9}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->fling(Ljava/lang/Object;IIIIIIII)V
a=0;// 
a=0;//     .line 197
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public fling(Ljava/lang/Object;IIIIIIIIII)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;//     .param p2, "startX"    # I
a=0;//     .param p3, "startY"    # I
a=0;//     .param p4, "velX"    # I
a=0;//     .param p5, "velY"    # I
a=0;//     .param p6, "minX"    # I
a=0;//     .param p7, "maxX"    # I
a=0;//     .param p8, "minY"    # I
a=0;//     .param p9, "maxY"    # I
a=0;//     .param p10, "overX"    # I
a=0;//     .param p11, "overY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 202
a=0;//     invoke-static/range {p1 .. p11}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->fling(Ljava/lang/Object;IIIIIIIIII)V
a=0;// 
a=0;//     .line 204
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public getCurrVelocity(Ljava/lang/Object;)F
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 173
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getCurrX(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 163
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->getCurrX(Ljava/lang/Object;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getCurrY(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 168
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->getCurrY(Ljava/lang/Object;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFinalX(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 229
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->getFinalX(Ljava/lang/Object;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFinalY(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 234
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->getFinalY(Ljava/lang/Object;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isFinished(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 158
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->isFinished(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isOverScrolled(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 224
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->isOverScrolled(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public notifyHorizontalEdgeReached(Ljava/lang/Object;III)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;//     .param p2, "startX"    # I
a=0;//     .param p3, "finalX"    # I
a=0;//     .param p4, "overX"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 214
a=0;//     invoke-static {p1, p2, p3, p4}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->notifyHorizontalEdgeReached(Ljava/lang/Object;III)V
a=0;// 
a=0;//     .line 215
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public notifyVerticalEdgeReached(Ljava/lang/Object;III)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;//     .param p2, "startY"    # I
a=0;//     .param p3, "finalY"    # I
a=0;//     .param p4, "overY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 219
a=0;//     invoke-static {p1, p2, p3, p4}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->notifyVerticalEdgeReached(Ljava/lang/Object;III)V
a=0;// 
a=0;//     .line 220
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public startScroll(Ljava/lang/Object;IIII)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;//     .param p2, "startX"    # I
a=0;//     .param p3, "startY"    # I
a=0;//     .param p4, "dx"    # I
a=0;//     .param p5, "dy"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 183
a=0;//     invoke-static {p1, p2, p3, p4, p5}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->startScroll(Ljava/lang/Object;IIII)V
a=0;// 
a=0;//     .line 184
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public startScroll(Ljava/lang/Object;IIIII)V
a=0;//     .locals 0
a=0;//     .param p1, "scroller"    # Ljava/lang/Object;
a=0;//     .param p2, "startX"    # I
a=0;//     .param p3, "startY"    # I
a=0;//     .param p4, "dx"    # I
a=0;//     .param p5, "dy"    # I
a=0;//     .param p6, "duration"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 189
a=0;//     invoke-static/range {p1 .. p6}, Landroid/support/v4/widget/ScrollerCompatGingerbread;->startScroll(Ljava/lang/Object;IIIII)V
a=0;// 
a=0;//     .line 190
a=0;//     return-void
a=0;// .end method
}}
