package android.support.v4.widget; class SearchViewCompat$SearchViewCompatImpl { void a() { int a;
a=0;// .class interface abstract Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SearchViewCompat.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/widget/SearchViewCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x608
a=0;//     name = "SearchViewCompatImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract getQuery(Landroid/view/View;)Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract isIconified(Landroid/view/View;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isQueryRefinementEnabled(Landroid/view/View;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isSubmitButtonEnabled(Landroid/view/View;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract newOnCloseListener(Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;)Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract newOnQueryTextListener(Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;)Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract newSearchView(Landroid/content/Context;)Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setIconified(Landroid/view/View;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setImeOptions(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setInputType(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setMaxWidth(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setOnCloseListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setOnQueryTextListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setQuery(Landroid/view/View;Ljava/lang/CharSequence;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setQueryHint(Landroid/view/View;Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setQueryRefinementEnabled(Landroid/view/View;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSearchableInfo(Landroid/view/View;Landroid/content/ComponentName;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubmitButtonEnabled(Landroid/view/View;Z)V
a=0;// .end method
}}
