package android.support.v4.widget; class SearchViewCompat$SearchViewCompatStubImpl { void a() { int a;
a=0;// .class Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatStubImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SearchViewCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/widget/SearchViewCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "SearchViewCompatStubImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatStubImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getQuery(Landroid/view/View;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public isIconified(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 109
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isQueryRefinementEnabled(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 127
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isSubmitButtonEnabled(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 118
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public newOnCloseListener(Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "listener"    # Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public newOnQueryTextListener(Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "listener"    # Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 74
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public newSearchView(Landroid/content/Context;)Landroid/view/View;
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setIconified(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "iconify"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 105
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setImeOptions(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "imeOptions"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 66
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setInputType(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "inputType"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 70
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMaxWidth(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "maxpixels"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 132
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOnCloseListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Ljava/lang/Object;
a=0;//     .param p2, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOnQueryTextListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Ljava/lang/Object;
a=0;//     .param p2, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setQuery(Landroid/view/View;Ljava/lang/CharSequence;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "query"    # Ljava/lang/CharSequence;
a=0;//     .param p3, "submit"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 97
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setQueryHint(Landroid/view/View;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "hint"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 101
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setQueryRefinementEnabled(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "enable"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 123
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSearchableInfo(Landroid/view/View;Landroid/content/ComponentName;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "searchableComponent"    # Landroid/content/ComponentName;
a=0;// 
a=0;//     .prologue
a=0;//     .line 62
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubmitButtonEnabled(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 114
a=0;//     return-void
a=0;// .end method
}}
