package android.support.v4.widget; class SearchViewCompatHoneycomb { void a() { int a;
a=0;// .class Landroid/support/v4/widget/SearchViewCompatHoneycomb;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SearchViewCompatHoneycomb.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;,
a=0;//         Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 37
a=0;//     #p0=(Reference,Landroid/support/v4/widget/SearchViewCompatHoneycomb;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getQuery(Landroid/view/View;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0}, Landroid/widget/SearchView;->getQuery()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static isIconified(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 100
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0}, Landroid/widget/SearchView;->isIconified()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isQueryRefinementEnabled(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0}, Landroid/widget/SearchView;->isQueryRefinementEnabled()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isSubmitButtonEnabled(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0}, Landroid/widget/SearchView;->isSubmitButtonEnabled()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static newOnCloseListener(Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "listener"    # Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     new-instance v0, Landroid/support/v4/widget/SearchViewCompatHoneycomb$2;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/widget/SearchViewCompatHoneycomb$2;);
a=0;//     invoke-direct {v0, p0}, Landroid/support/v4/widget/SearchViewCompatHoneycomb$2;-><init>(Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/widget/SearchViewCompatHoneycomb$2;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static newOnQueryTextListener(Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "listener"    # Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     new-instance v0, Landroid/support/v4/widget/SearchViewCompatHoneycomb$1;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/widget/SearchViewCompatHoneycomb$1;);
a=0;//     invoke-direct {v0, p0}, Landroid/support/v4/widget/SearchViewCompatHoneycomb$1;-><init>(Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/widget/SearchViewCompatHoneycomb$1;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static newSearchView(Landroid/content/Context;)Landroid/view/View;
a=0;//     .locals 1
a=0;//     .param p0, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     new-instance v0, Landroid/widget/SearchView;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/widget/SearchView;);
a=0;//     invoke-direct {v0, p0}, Landroid/widget/SearchView;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/SearchView;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static setIconified(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "iconify"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setIconified(Z)V
a=0;// 
a=0;//     .line 97
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setMaxWidth(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "maxpixels"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 120
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setMaxWidth(I)V
a=0;// 
a=0;//     .line 121
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setOnCloseListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Ljava/lang/Object;
a=0;//     .param p1, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Ljava/lang/Object;
a=0;//     check-cast p1, Landroid/widget/SearchView$OnCloseListener;
a=0;// 
a=0;//     .end local p1    # "listener":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setOnCloseListener(Landroid/widget/SearchView$OnCloseListener;)V
a=0;// 
a=0;//     .line 81
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setOnQueryTextListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Ljava/lang/Object;
a=0;//     .param p1, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Ljava/lang/Object;
a=0;//     check-cast p1, Landroid/widget/SearchView$OnQueryTextListener;
a=0;// 
a=0;//     .end local p1    # "listener":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setOnQueryTextListener(Landroid/widget/SearchView$OnQueryTextListener;)V
a=0;// 
a=0;//     .line 68
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setQuery(Landroid/view/View;Ljava/lang/CharSequence;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "query"    # Ljava/lang/CharSequence;
a=0;//     .param p2, "submit"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/widget/SearchView;->setQuery(Ljava/lang/CharSequence;Z)V
a=0;// 
a=0;//     .line 89
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setQueryHint(Landroid/view/View;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "hint"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setQueryHint(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 93
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setQueryRefinementEnabled(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "enable"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setQueryRefinementEnabled(Z)V
a=0;// 
a=0;//     .line 113
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setSearchableInfo(Landroid/view/View;Landroid/content/ComponentName;)V
a=0;//     .locals 4
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "searchableComponent"    # Landroid/content/ComponentName;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     move-object v1, p0
a=0;// 
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     check-cast v1, Landroid/widget/SearchView;
a=0;// 
a=0;//     .line 47
a=0;//     .local v1, "sv":Landroid/widget/SearchView;
a=0;//     invoke-virtual {v1}, Landroid/widget/SearchView;->getContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/Context;);
a=0;//     const-string v3, "search"
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/Context;->getSystemService(Ljava/lang/String;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Landroid/app/SearchManager;
a=0;// 
a=0;//     .line 49
a=0;//     .local v0, "searchManager":Landroid/app/SearchManager;
a=0;//     invoke-virtual {v0, p1}, Landroid/app/SearchManager;->getSearchableInfo(Landroid/content/ComponentName;)Landroid/app/SearchableInfo;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/SearchView;->setSearchableInfo(Landroid/app/SearchableInfo;)V
a=0;// 
a=0;//     .line 50
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setSubmitButtonEnabled(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "searchView"    # Landroid/view/View;
a=0;//     .param p1, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     check-cast p0, Landroid/widget/SearchView;
a=0;// 
a=0;//     .end local p0    # "searchView":Landroid/view/View;
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/SearchView;->setSubmitButtonEnabled(Z)V
a=0;// 
a=0;//     .line 105
a=0;//     return-void
a=0;// .end method
}}
