package android.support.v4.widget; class SearchViewCompat$SearchViewCompatHoneycombImpl { void a() { int a;
a=0;// .class Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl;
a=0;// .super Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatStubImpl;
a=0;// .source "SearchViewCompat.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/widget/SearchViewCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "SearchViewCompatHoneycombImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 135
a=0;//     invoke-direct {p0}, Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatStubImpl;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getQuery(Landroid/view/View;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 185
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->getQuery(Landroid/view/View;)Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public isIconified(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 205
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->isIconified(Landroid/view/View;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isQueryRefinementEnabled(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 225
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->isQueryRefinementEnabled(Landroid/view/View;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isSubmitButtonEnabled(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 215
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->isSubmitButtonEnabled(Landroid/view/View;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public newOnCloseListener(Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "listener"    # Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 169
a=0;//     new-instance v0, Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$2;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$2;);
a=0;//     invoke-direct {v0, p0, p1}, Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$2;-><init>(Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl;Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$2;);
a=0;//     invoke-static {v0}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->newOnCloseListener(Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public newOnQueryTextListener(Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "listener"    # Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 149
a=0;//     new-instance v0, Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$1;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$1;);
a=0;//     invoke-direct {v0, p0, p1}, Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$1;-><init>(Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl;Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$1;);
a=0;//     invoke-static {v0}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->newOnQueryTextListener(Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public newSearchView(Landroid/content/Context;)Landroid/view/View;
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     invoke-static {p1}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->newSearchView(Landroid/content/Context;)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setIconified(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "iconify"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 200
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setIconified(Landroid/view/View;Z)V
a=0;// 
a=0;//     .line 201
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMaxWidth(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "maxpixels"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 230
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setMaxWidth(Landroid/view/View;I)V
a=0;// 
a=0;//     .line 231
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOnCloseListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Ljava/lang/Object;
a=0;//     .param p2, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 180
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setOnCloseListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;// 
a=0;//     .line 181
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOnQueryTextListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Ljava/lang/Object;
a=0;//     .param p2, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 164
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setOnQueryTextListener(Ljava/lang/Object;Ljava/lang/Object;)V
a=0;// 
a=0;//     .line 165
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setQuery(Landroid/view/View;Ljava/lang/CharSequence;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "query"    # Ljava/lang/CharSequence;
a=0;//     .param p3, "submit"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 190
a=0;//     invoke-static {p1, p2, p3}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setQuery(Landroid/view/View;Ljava/lang/CharSequence;Z)V
a=0;// 
a=0;//     .line 191
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setQueryHint(Landroid/view/View;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "hint"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 195
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setQueryHint(Landroid/view/View;Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 196
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setQueryRefinementEnabled(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "enable"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 220
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setQueryRefinementEnabled(Landroid/view/View;Z)V
a=0;// 
a=0;//     .line 221
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSearchableInfo(Landroid/view/View;Landroid/content/ComponentName;)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "searchableComponent"    # Landroid/content/ComponentName;
a=0;// 
a=0;//     .prologue
a=0;//     .line 144
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setSearchableInfo(Landroid/view/View;Landroid/content/ComponentName;)V
a=0;// 
a=0;//     .line 145
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubmitButtonEnabled(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "searchView"    # Landroid/view/View;
a=0;//     .param p2, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 210
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/widget/SearchViewCompatHoneycomb;->setSubmitButtonEnabled(Landroid/view/View;Z)V
a=0;// 
a=0;//     .line 211
a=0;//     return-void
a=0;// .end method
}}
