package android.support.v4.widget; class SwipeRefreshLayout$BaseAnimationListener { void a() { int a;
a=0;// .class Landroid/support/v4/widget/SwipeRefreshLayout$BaseAnimationListener;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SwipeRefreshLayout.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/view/animation/Animation$AnimationListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/widget/SwipeRefreshLayout;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x2
a=0;//     name = "BaseAnimationListener"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Landroid/support/v4/widget/SwipeRefreshLayout;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>(Landroid/support/v4/widget/SwipeRefreshLayout;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 577
a=0;//     iput-object p1, p0, Landroid/support/v4/widget/SwipeRefreshLayout$BaseAnimationListener;->this$0:Landroid/support/v4/widget/SwipeRefreshLayout;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/widget/SwipeRefreshLayout$BaseAnimationListener;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method synthetic constructor <init>(Landroid/support/v4/widget/SwipeRefreshLayout;Landroid/support/v4/widget/SwipeRefreshLayout$1;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v4/widget/SwipeRefreshLayout;
a=0;//     .param p2, "x1"    # Landroid/support/v4/widget/SwipeRefreshLayout$1;
a=0;// 
a=0;//     .prologue
a=0;//     .line 577
a=0;//     invoke-direct {p0, p1}, Landroid/support/v4/widget/SwipeRefreshLayout$BaseAnimationListener;-><init>(Landroid/support/v4/widget/SwipeRefreshLayout;)V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/widget/SwipeRefreshLayout$BaseAnimationListener;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onAnimationEnd(Landroid/view/animation/Animation;)V
a=0;//     .locals 0
a=0;//     .param p1, "animation"    # Landroid/view/animation/Animation;
a=0;// 
a=0;//     .prologue
a=0;//     .line 584
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onAnimationRepeat(Landroid/view/animation/Animation;)V
a=0;//     .locals 0
a=0;//     .param p1, "animation"    # Landroid/view/animation/Animation;
a=0;// 
a=0;//     .prologue
a=0;//     .line 588
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onAnimationStart(Landroid/view/animation/Animation;)V
a=0;//     .locals 0
a=0;//     .param p1, "animation"    # Landroid/view/animation/Animation;
a=0;// 
a=0;//     .prologue
a=0;//     .line 580
a=0;//     return-void
a=0;// .end method
}}
