package android.support.v7.app; class ActionBarImplICS { void a() { int a;
a=0;// .class Landroid/support/v7/app/ActionBarImplICS;
a=0;// .super Landroid/support/v7/app/ActionBar;
a=0;// .source "ActionBarImplICS.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v7/app/ActionBarImplICS$TabWrapper;,
a=0;//         Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;,
a=0;//         Landroid/support/v7/app/ActionBarImplICS$OnNavigationListenerWrapper;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;// .field mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;// .field final mActivity:Landroid/app/Activity;
a=0;// 
a=0;// .field private mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Ljava/lang/ref/WeakReference",
a=0;//             "<",
a=0;//             "Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;",
a=0;//             ">;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field final mCallback:Landroid/support/v7/app/ActionBar$Callback;
a=0;// 
a=0;// .field private mHomeActionView:Landroid/widget/ImageView;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/app/Activity;Landroid/support/v7/app/ActionBar$Callback;)V
a=0;//     .locals 1
a=0;//     .param p1, "activity"    # Landroid/app/Activity;
a=0;//     .param p2, "callback"    # Landroid/support/v7/app/ActionBar$Callback;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     invoke-direct {p0, p1, p2, v0}, Landroid/support/v7/app/ActionBarImplICS;-><init>(Landroid/app/Activity;Landroid/support/v7/app/ActionBar$Callback;Z)V
a=0;// 
a=0;//     .line 47
a=0;//     #p0=(Reference,Landroid/support/v7/app/ActionBarImplICS;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method constructor <init>(Landroid/app/Activity;Landroid/support/v7/app/ActionBar$Callback;Z)V
a=0;//     .locals 1
a=0;//     .param p1, "activity"    # Landroid/app/Activity;
a=0;//     .param p2, "callback"    # Landroid/support/v7/app/ActionBar$Callback;
a=0;//     .param p3, "checkHomeAsUpOption"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 49
a=0;//     invoke-direct {p0}, Landroid/support/v7/app/ActionBar;-><init>()V
a=0;// 
a=0;//     .line 42
a=0;//     #p0=(Reference,Landroid/support/v7/app/ActionBarImplICS;);
a=0;//     new-instance v0, Ljava/util/ArrayList;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/util/ArrayList;);
a=0;//     invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/ArrayList;);
a=0;//     iput-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;// 
a=0;//     .line 50
a=0;//     iput-object p1, p0, Landroid/support/v7/app/ActionBarImplICS;->mActivity:Landroid/app/Activity;
a=0;// 
a=0;//     .line 51
a=0;//     iput-object p2, p0, Landroid/support/v7/app/ActionBarImplICS;->mCallback:Landroid/support/v7/app/ActionBar$Callback;
a=0;// 
a=0;//     .line 52
a=0;//     invoke-virtual {p1}, Landroid/app/Activity;->getActionBar()Landroid/app/ActionBar;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     .line 54
a=0;//     if-eqz p3, :cond_0
a=0;// 
a=0;//     .line 57
a=0;//     invoke-virtual {p0}, Landroid/support/v7/app/ActionBarImplICS;->getDisplayOptions()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     and-int/lit8 v0, v0, 0x4
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 58
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     invoke-virtual {p0, v0}, Landroid/support/v7/app/ActionBarImplICS;->setHomeButtonEnabled(Z)V
a=0;// 
a=0;//     .line 61
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private findAndRemoveMenuVisWrapper(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;//     .locals 4
a=0;//     .param p1, "compatListener"    # Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .local v0, "i":I
a=0;//     :goto_0
a=0;//     #v0=(Integer);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);
a=0;//     iget-object v3, p0, Landroid/support/v7/app/ActionBarImplICS;->mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v3=(Reference,Ljava/util/ArrayList;);
a=0;//     invoke-virtual {v3}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     if-ge v0, v3, :cond_2
a=0;// 
a=0;//     .line 66
a=0;//     iget-object v3, p0, Landroid/support/v7/app/ActionBarImplICS;->mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v3=(Reference,Ljava/util/ArrayList;);
a=0;//     invoke-virtual {v3, v0}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     check-cast v3, Ljava/lang/ref/WeakReference;
a=0;// 
a=0;//     invoke-virtual {v3}, Ljava/lang/ref/WeakReference;->get()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v2, Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;// 
a=0;//     .line 67
a=0;//     .local v2, "wrapper":Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;//     if-nez v2, :cond_1
a=0;// 
a=0;//     .line 68
a=0;//     iget-object v3, p0, Landroid/support/v7/app/ActionBarImplICS;->mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;// 
a=0;//     add-int/lit8 v1, v0, -0x1
a=0;// 
a=0;//     .end local v0    # "i":I
a=0;//     .local v1, "i":I
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v3, v0}, Ljava/util/ArrayList;->remove(I)Ljava/lang/Object;
a=0;// 
a=0;//     move v0, v1
a=0;// 
a=0;//     .line 65
a=0;//     .end local v1    # "i":I
a=0;//     .restart local v0    # "i":I
a=0;//     :cond_0
a=0;//     #v1=(Conflicted);
a=0;//     add-int/lit8 v0, v0, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 69
a=0;//     :cond_1
a=0;//     iget-object v3, v2, Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;->mWrappedListener:Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;
a=0;// 
a=0;//     if-ne v3, p1, :cond_0
a=0;// 
a=0;//     .line 70
a=0;//     iget-object v3, p0, Landroid/support/v7/app/ActionBarImplICS;->mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-virtual {v3, v0}, Ljava/util/ArrayList;->remove(I)Ljava/lang/Object;
a=0;// 
a=0;//     .line 74
a=0;//     .end local v2    # "wrapper":Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;//     :goto_1
a=0;//     #v3=(Conflicted);
a=0;//     return-object v2
a=0;// 
a=0;//     :cond_2
a=0;//     #v2=(Conflicted);v3=(Integer);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public addOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;//     .locals 3
a=0;//     .param p1, "listener"    # Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 350
a=0;//     if-eqz p1, :cond_0
a=0;// 
a=0;//     .line 351
a=0;//     new-instance v0, Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;);
a=0;//     invoke-direct {v0, p1}, Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;-><init>(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// 
a=0;//     .line 352
a=0;//     .local v0, "w":Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;);
a=0;//     iget-object v1, p0, Landroid/support/v7/app/ActionBarImplICS;->mAddedMenuVisWrappers:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v1=(Reference,Ljava/util/ArrayList;);
a=0;//     new-instance v2, Ljava/lang/ref/WeakReference;
a=0;// 
a=0;//     #v2=(UninitRef,Ljava/lang/ref/WeakReference;);
a=0;//     invoke-direct {v2, v0}, Ljava/lang/ref/WeakReference;-><init>(Ljava/lang/Object;)V
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/ref/WeakReference;);
a=0;//     invoke-virtual {v1, v2}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z
a=0;// 
a=0;//     .line 353
a=0;//     iget-object v1, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/app/ActionBar;->addOnMenuVisibilityListener(Landroid/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// 
a=0;//     .line 355
a=0;//     .end local v0    # "w":Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public addTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;//     .locals 2
a=0;//     .param p1, "tab"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     .prologue
a=0;//     .line 247
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     check-cast p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     .end local p1    # "tab":Landroid/support/v7/app/ActionBar$Tab;
a=0;//     iget-object v1, p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;->mWrappedTab:Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     invoke-virtual {v0, v1}, Landroid/app/ActionBar;->addTab(Landroid/app/ActionBar$Tab;)V
a=0;// 
a=0;//     .line 248
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public addTab(Landroid/support/v7/app/ActionBar$Tab;I)V
a=0;//     .locals 2
a=0;//     .param p1, "tab"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .param p2, "position"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 257
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     check-cast p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     .end local p1    # "tab":Landroid/support/v7/app/ActionBar$Tab;
a=0;//     iget-object v1, p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;->mWrappedTab:Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     invoke-virtual {v0, v1, p2}, Landroid/app/ActionBar;->addTab(Landroid/app/ActionBar$Tab;I)V
a=0;// 
a=0;//     .line 258
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public addTab(Landroid/support/v7/app/ActionBar$Tab;IZ)V
a=0;//     .locals 2
a=0;//     .param p1, "tab"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .param p2, "position"    # I
a=0;//     .param p3, "setSelected"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 262
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     check-cast p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     .end local p1    # "tab":Landroid/support/v7/app/ActionBar$Tab;
a=0;//     iget-object v1, p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;->mWrappedTab:Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     invoke-virtual {v0, v1, p2, p3}, Landroid/app/ActionBar;->addTab(Landroid/app/ActionBar$Tab;IZ)V
a=0;// 
a=0;//     .line 263
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public addTab(Landroid/support/v7/app/ActionBar$Tab;Z)V
a=0;//     .locals 2
a=0;//     .param p1, "tab"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .param p2, "setSelected"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 252
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     check-cast p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     .end local p1    # "tab":Landroid/support/v7/app/ActionBar$Tab;
a=0;//     iget-object v1, p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;->mWrappedTab:Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     invoke-virtual {v0, v1, p2}, Landroid/app/ActionBar;->addTab(Landroid/app/ActionBar$Tab;Z)V
a=0;// 
a=0;//     .line 253
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method commitActiveTransaction()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 377
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/app/FragmentTransaction;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentTransaction;->isEmpty()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 378
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/app/FragmentTransaction;);
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentTransaction;->commit()I
a=0;// 
a=0;//     .line 380
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     .line 381
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method getActiveTransaction()Landroid/support/v4/app/FragmentTransaction;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 369
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/app/FragmentTransaction;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 370
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mCallback:Landroid/support/v7/app/ActionBar$Callback;
a=0;// 
a=0;//     invoke-interface {v0}, Landroid/support/v7/app/ActionBar$Callback;->getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentManager;->beginTransaction()Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentTransaction;->disallowAddToBackStack()Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     .line 373
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActiveTransaction:Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCustomView()Landroid/view/View;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 209
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getCustomView()Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDisplayOptions()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 234
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getDisplayOptions()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getHeight()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 330
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getHeight()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method getHomeActionView()Landroid/widget/ImageView;
a=0;//     .locals 9
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v6, 0x0
a=0;// 
a=0;//     #v6=(Null);
a=0;//     const v8, 0x102002c
a=0;// 
a=0;//     .line 384
a=0;//     #v8=(Integer);
a=0;//     iget-object v7, p0, Landroid/support/v7/app/ActionBarImplICS;->mHomeActionView:Landroid/widget/ImageView;
a=0;// 
a=0;//     #v7=(Reference,Landroid/widget/ImageView;);
a=0;//     if-nez v7, :cond_2
a=0;// 
a=0;//     .line 385
a=0;//     iget-object v7, p0, Landroid/support/v7/app/ActionBarImplICS;->mActivity:Landroid/app/Activity;
a=0;// 
a=0;//     invoke-virtual {v7, v8}, Landroid/app/Activity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 386
a=0;//     .local v2, "home":Landroid/view/View;
a=0;//     #v2=(Reference,Landroid/view/View;);
a=0;//     if-nez v2, :cond_1
a=0;// 
a=0;//     .line 407
a=0;//     .end local v2    # "home":Landroid/view/View;
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);v5=(Conflicted);v6=(Reference,Landroid/widget/ImageView;);v7=(Conflicted);
a=0;//     return-object v6
a=0;// 
a=0;//     .line 391
a=0;//     .restart local v2    # "home":Landroid/view/View;
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Reference,Landroid/view/View;);v3=(Uninit);v4=(Uninit);v5=(Uninit);v6=(Null);v7=(Reference,Landroid/app/Activity;);
a=0;//     invoke-virtual {v2}, Landroid/view/View;->getParent()Landroid/view/ViewParent;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     #v3=(Reference,Landroid/view/ViewParent;);
a=0;//     check-cast v3, Landroid/view/ViewGroup;
a=0;// 
a=0;//     .line 392
a=0;//     .local v3, "parent":Landroid/view/ViewGroup;
a=0;//     invoke-virtual {v3}, Landroid/view/ViewGroup;->getChildCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 393
a=0;//     .local v0, "childCount":I
a=0;//     #v0=(Integer);
a=0;//     const/4 v7, 0x2
a=0;// 
a=0;//     #v7=(PosByte);
a=0;//     if-ne v0, v7, :cond_0
a=0;// 
a=0;//     .line 398
a=0;//     const/4 v6, 0x0
a=0;// 
a=0;//     invoke-virtual {v3, v6}, Landroid/view/ViewGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 399
a=0;//     .local v1, "first":Landroid/view/View;
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     const/4 v6, 0x1
a=0;// 
a=0;//     #v6=(One);
a=0;//     invoke-virtual {v3, v6}, Landroid/view/ViewGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     .line 400
a=0;//     .local v4, "second":Landroid/view/View;
a=0;//     #v4=(Reference,Landroid/view/View;);
a=0;//     invoke-virtual {v1}, Landroid/view/View;->getId()I
a=0;// 
a=0;//     move-result v6
a=0;// 
a=0;//     #v6=(Integer);
a=0;//     if-ne v6, v8, :cond_3
a=0;// 
a=0;//     move-object v5, v4
a=0;// 
a=0;//     .line 402
a=0;//     .local v5, "up":Landroid/view/View;
a=0;//     :goto_1
a=0;//     #v5=(Reference,Landroid/view/View;);
a=0;//     instance-of v6, v5, Landroid/widget/ImageView;
a=0;// 
a=0;//     #v6=(Boolean);
a=0;//     if-eqz v6, :cond_2
a=0;// 
a=0;//     .line 404
a=0;//     check-cast v5, Landroid/widget/ImageView;
a=0;// 
a=0;//     .end local v5    # "up":Landroid/view/View;
a=0;//     iput-object v5, p0, Landroid/support/v7/app/ActionBarImplICS;->mHomeActionView:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 407
a=0;//     .end local v0    # "childCount":I
a=0;//     .end local v1    # "first":Landroid/view/View;
a=0;//     .end local v2    # "home":Landroid/view/View;
a=0;//     .end local v3    # "parent":Landroid/view/ViewGroup;
a=0;//     .end local v4    # "second":Landroid/view/View;
a=0;//     :cond_2
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);v5=(Conflicted);v7=(Conflicted);
a=0;//     iget-object v6, p0, Landroid/support/v7/app/ActionBarImplICS;->mHomeActionView:Landroid/widget/ImageView;
a=0;// 
a=0;//     #v6=(Reference,Landroid/widget/ImageView;);
a=0;//     goto :goto_0
a=0;// 
a=0;//     .restart local v0    # "childCount":I
a=0;//     .restart local v1    # "first":Landroid/view/View;
a=0;//     .restart local v2    # "home":Landroid/view/View;
a=0;//     .restart local v3    # "parent":Landroid/view/ViewGroup;
a=0;//     .restart local v4    # "second":Landroid/view/View;
a=0;//     :cond_3
a=0;//     #v0=(Integer);v1=(Reference,Landroid/view/View;);v2=(Reference,Landroid/view/View;);v3=(Reference,Landroid/view/ViewGroup;);v4=(Reference,Landroid/view/View;);v5=(Uninit);v6=(Integer);v7=(PosByte);
a=0;//     move-object v5, v1
a=0;// 
a=0;//     .line 400
a=0;//     #v5=(Reference,Landroid/view/View;);
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// .method public getNavigationItemCount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 134
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getNavigationItemCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getNavigationMode()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 224
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getNavigationMode()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSelectedNavigationIndex()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 129
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getSelectedNavigationIndex()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSelectedTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 287
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getSelectedTab()Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar$Tab;->getTag()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSubtitle()Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 219
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getSubtitle()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTabAt(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .locals 1
a=0;//     .param p1, "index"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 292
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->getTabAt(I)Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar$Tab;->getTag()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTabCount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 297
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getTabCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method getThemeDefaultUpIndicator()Landroid/graphics/drawable/Drawable;
a=0;//     .locals 6
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v5, 0x0
a=0;// 
a=0;//     .line 411
a=0;//     #v5=(Null);
a=0;//     iget-object v2, p0, Landroid/support/v7/app/ActionBarImplICS;->mActivity:Landroid/app/Activity;
a=0;// 
a=0;//     #v2=(Reference,Landroid/app/Activity;);
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     #v3=(One);
a=0;//     new-array v3, v3, [I
a=0;// 
a=0;//     #v3=(Reference,[I);
a=0;//     const v4, 0x101030b
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     aput v4, v3, v5
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/app/Activity;->obtainStyledAttributes([I)Landroid/content/res/TypedArray;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 413
a=0;//     .local v0, "a":Landroid/content/res/TypedArray;
a=0;//     #v0=(Reference,Landroid/content/res/TypedArray;);
a=0;//     invoke-virtual {v0, v5}, Landroid/content/res/TypedArray;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 414
a=0;//     .local v1, "result":Landroid/graphics/drawable/Drawable;
a=0;//     #v1=(Reference,Landroid/graphics/drawable/Drawable;);
a=0;//     invoke-virtual {v0}, Landroid/content/res/TypedArray;->recycle()V
a=0;// 
a=0;//     .line 415
a=0;//     return-object v1
a=0;// .end method
a=0;// 
a=0;// .method public getThemedContext()Landroid/content/Context;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 302
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getThemedContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTitle()Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 214
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->getTitle()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public hide()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 340
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->hide()V
a=0;// 
a=0;//     .line 341
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public isShowing()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 345
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->isShowing()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public newTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 239
a=0;//     iget-object v2, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v2=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v2}, Landroid/app/ActionBar;->newTab()Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 240
a=0;//     .local v0, "realTab":Landroid/app/ActionBar$Tab;
a=0;//     #v0=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     new-instance v1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     #v1=(UninitRef,Landroid/support/v7/app/ActionBarImplICS$TabWrapper;);
a=0;//     invoke-direct {v1, p0, v0}, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;-><init>(Landroid/support/v7/app/ActionBarImplICS;Landroid/app/ActionBar$Tab;)V
a=0;// 
a=0;//     .line 241
a=0;//     .local v1, "result":Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;//     #v1=(Reference,Landroid/support/v7/app/ActionBarImplICS$TabWrapper;);
a=0;//     invoke-virtual {v0, v1}, Landroid/app/ActionBar$Tab;->setTag(Ljava/lang/Object;)Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     .line 242
a=0;//     return-object v1
a=0;// .end method
a=0;// 
a=0;// .method public removeAllTabs()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 277
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->removeAllTabs()V
a=0;// 
a=0;//     .line 278
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public removeOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;//     .locals 2
a=0;//     .param p1, "listener"    # Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 359
a=0;//     invoke-direct {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->findAndRemoveMenuVisWrapper(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 360
a=0;//     .local v0, "l":Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBarImplICS$OnMenuVisibilityListenerWrapper;);
a=0;//     iget-object v1, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v1, v0}, Landroid/app/ActionBar;->removeOnMenuVisibilityListener(Landroid/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// 
a=0;//     .line 361
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public removeTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;//     .locals 2
a=0;//     .param p1, "tab"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     .prologue
a=0;//     .line 267
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     check-cast p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     .end local p1    # "tab":Landroid/support/v7/app/ActionBar$Tab;
a=0;//     iget-object v1, p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;->mWrappedTab:Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     invoke-virtual {v0, v1}, Landroid/app/ActionBar;->removeTab(Landroid/app/ActionBar$Tab;)V
a=0;// 
a=0;//     .line 268
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public removeTabAt(I)V
a=0;//     .locals 1
a=0;//     .param p1, "position"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 272
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->removeTabAt(I)V
a=0;// 
a=0;//     .line 273
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public selectTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;//     .locals 2
a=0;//     .param p1, "tab"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     .prologue
a=0;//     .line 282
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     check-cast p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;
a=0;// 
a=0;//     .end local p1    # "tab":Landroid/support/v7/app/ActionBar$Tab;
a=0;//     iget-object v1, p1, Landroid/support/v7/app/ActionBarImplICS$TabWrapper;->mWrappedTab:Landroid/app/ActionBar$Tab;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar$Tab;);
a=0;//     invoke-virtual {v0, v1}, Landroid/app/ActionBar;->selectTab(Landroid/app/ActionBar$Tab;)V
a=0;// 
a=0;//     .line 283
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 1
a=0;//     .param p1, "d"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 194
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 195
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCustomView(I)V
a=0;//     .locals 1
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 93
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setCustomView(I)V
a=0;// 
a=0;//     .line 94
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCustomView(Landroid/view/View;)V
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setCustomView(Landroid/view/View;)V
a=0;// 
a=0;//     .line 80
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCustomView(Landroid/view/View;Landroid/support/v7/app/ActionBar$LayoutParams;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "layoutParams"    # Landroid/support/v7/app/ActionBar$LayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     new-instance v0, Landroid/app/ActionBar$LayoutParams;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/app/ActionBar$LayoutParams;);
a=0;//     invoke-direct {v0, p2}, Landroid/app/ActionBar$LayoutParams;-><init>(Landroid/view/ViewGroup$LayoutParams;)V
a=0;// 
a=0;//     .line 86
a=0;//     .local v0, "lp":Landroid/app/ActionBar$LayoutParams;
a=0;//     #v0=(Reference,Landroid/app/ActionBar$LayoutParams;);
a=0;//     iget v1, p2, Landroid/support/v7/app/ActionBar$LayoutParams;->gravity:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     iput v1, v0, Landroid/app/ActionBar$LayoutParams;->gravity:I
a=0;// 
a=0;//     .line 88
a=0;//     iget-object v1, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v1, p1, v0}, Landroid/app/ActionBar;->setCustomView(Landroid/view/View;Landroid/app/ActionBar$LayoutParams;)V
a=0;// 
a=0;//     .line 89
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayHomeAsUpEnabled(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "showHomeAsUp"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 179
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setDisplayHomeAsUpEnabled(Z)V
a=0;// 
a=0;//     .line 180
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayOptions(I)V
a=0;//     .locals 1
a=0;//     .param p1, "options"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 159
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setDisplayOptions(I)V
a=0;// 
a=0;//     .line 160
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayOptions(II)V
a=0;//     .locals 1
a=0;//     .param p1, "options"    # I
a=0;//     .param p2, "mask"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 164
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1, p2}, Landroid/app/ActionBar;->setDisplayOptions(II)V
a=0;// 
a=0;//     .line 165
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayShowCustomEnabled(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "showCustom"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 189
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setDisplayShowCustomEnabled(Z)V
a=0;// 
a=0;//     .line 190
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayShowHomeEnabled(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "showHome"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 174
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setDisplayShowHomeEnabled(Z)V
a=0;// 
a=0;//     .line 175
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayShowTitleEnabled(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "showTitle"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 184
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setDisplayShowTitleEnabled(Z)V
a=0;// 
a=0;//     .line 185
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayUseLogoEnabled(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "useLogo"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 169
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setDisplayUseLogoEnabled(Z)V
a=0;// 
a=0;//     .line 170
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHomeAsUpIndicator(I)V
a=0;//     .locals 2
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 318
a=0;//     invoke-virtual {p0}, Landroid/support/v7/app/ActionBarImplICS;->getHomeActionView()Landroid/widget/ImageView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 319
a=0;//     .local v0, "homeActionView":Landroid/widget/ImageView;
a=0;//     #v0=(Reference,Landroid/widget/ImageView;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 320
a=0;//     if-eqz p1, :cond_1
a=0;// 
a=0;//     .line 321
a=0;//     invoke-virtual {v0, p1}, Landroid/widget/ImageView;->setImageResource(I)V
a=0;// 
a=0;//     .line 326
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v1=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 323
a=0;//     :cond_1
a=0;//     #v1=(Uninit);
a=0;//     invoke-virtual {p0}, Landroid/support/v7/app/ActionBarImplICS;->getThemeDefaultUpIndicator()Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/graphics/drawable/Drawable;);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/ImageView;->setImageDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public setHomeAsUpIndicator(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 1
a=0;//     .param p1, "indicator"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 307
a=0;//     invoke-virtual {p0}, Landroid/support/v7/app/ActionBarImplICS;->getHomeActionView()Landroid/widget/ImageView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 308
a=0;//     .local v0, "homeActionView":Landroid/widget/ImageView;
a=0;//     #v0=(Reference,Landroid/widget/ImageView;);
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     .line 309
a=0;//     if-nez p1, :cond_0
a=0;// 
a=0;//     .line 310
a=0;//     invoke-virtual {p0}, Landroid/support/v7/app/ActionBarImplICS;->getThemeDefaultUpIndicator()Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object p1
a=0;// 
a=0;//     .line 312
a=0;//     :cond_0
a=0;//     invoke-virtual {v0, p1}, Landroid/widget/ImageView;->setImageDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 314
a=0;//     :cond_1
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHomeButtonEnabled(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 365
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setHomeButtonEnabled(Z)V
a=0;// 
a=0;//     .line 366
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIcon(I)V
a=0;//     .locals 1
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 98
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setIcon(I)V
a=0;// 
a=0;//     .line 99
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIcon(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 1
a=0;//     .param p1, "icon"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 103
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setIcon(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 104
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setListNavigationCallbacks(Landroid/widget/SpinnerAdapter;Landroid/support/v7/app/ActionBar$OnNavigationListener;)V
a=0;//     .locals 2
a=0;//     .param p1, "adapter"    # Landroid/widget/SpinnerAdapter;
a=0;//     .param p2, "callback"    # Landroid/support/v7/app/ActionBar$OnNavigationListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 118
a=0;//     iget-object v1, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v1=(Reference,Landroid/app/ActionBar;);
a=0;//     if-eqz p2, :cond_0
a=0;// 
a=0;//     new-instance v0, Landroid/support/v7/app/ActionBarImplICS$OnNavigationListenerWrapper;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v7/app/ActionBarImplICS$OnNavigationListenerWrapper;);
a=0;//     invoke-direct {v0, p2}, Landroid/support/v7/app/ActionBarImplICS$OnNavigationListenerWrapper;-><init>(Landroid/support/v7/app/ActionBar$OnNavigationListener;)V
a=0;// 
a=0;//     :goto_0
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBarImplICS$OnNavigationListenerWrapper;);
a=0;//     invoke-virtual {v1, p1, v0}, Landroid/app/ActionBar;->setListNavigationCallbacks(Landroid/widget/SpinnerAdapter;Landroid/app/ActionBar$OnNavigationListener;)V
a=0;// 
a=0;//     .line 120
a=0;//     return-void
a=0;// 
a=0;//     .line 118
a=0;//     :cond_0
a=0;//     #v0=(Uninit);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public setLogo(I)V
a=0;//     .locals 1
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setLogo(I)V
a=0;// 
a=0;//     .line 109
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLogo(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 1
a=0;//     .param p1, "logo"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 113
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setLogo(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 114
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setNavigationMode(I)V
a=0;//     .locals 1
a=0;//     .param p1, "mode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 229
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setNavigationMode(I)V
a=0;// 
a=0;//     .line 230
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSelectedNavigationItem(I)V
a=0;//     .locals 1
a=0;//     .param p1, "position"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 124
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setSelectedNavigationItem(I)V
a=0;// 
a=0;//     .line 125
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSplitBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 1
a=0;//     .param p1, "d"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 204
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setSplitBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 205
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStackedBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 1
a=0;//     .param p1, "d"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 199
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setStackedBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 200
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubtitle(I)V
a=0;//     .locals 1
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 154
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setSubtitle(I)V
a=0;// 
a=0;//     .line 155
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubtitle(Ljava/lang/CharSequence;)V
a=0;//     .locals 1
a=0;//     .param p1, "subtitle"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 149
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setSubtitle(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 150
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTitle(I)V
a=0;//     .locals 1
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 144
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setTitle(I)V
a=0;// 
a=0;//     .line 145
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTitle(Ljava/lang/CharSequence;)V
a=0;//     .locals 1
a=0;//     .param p1, "title"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0, p1}, Landroid/app/ActionBar;->setTitle(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 140
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public show()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 335
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplICS;->mActionBar:Landroid/app/ActionBar;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ActionBar;);
a=0;//     invoke-virtual {v0}, Landroid/app/ActionBar;->show()V
a=0;// 
a=0;//     .line 336
a=0;//     return-void
a=0;// .end method
}}
