package android.support.v7.app; class ActionBarImplJB { void a() { int a;
a=0;// .class public Landroid/support/v7/app/ActionBarImplJB;
a=0;// .super Landroid/support/v7/app/ActionBarImplICS;
a=0;// .source "ActionBarImplJB.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/app/Activity;Landroid/support/v7/app/ActionBar$Callback;)V
a=0;//     .locals 1
a=0;//     .param p1, "activity"    # Landroid/app/Activity;
a=0;//     .param p2, "callback"    # Landroid/support/v7/app/ActionBar$Callback;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     invoke-direct {p0, p1, p2, v0}, Landroid/support/v7/app/ActionBarImplICS;-><init>(Landroid/app/Activity;Landroid/support/v7/app/ActionBar$Callback;Z)V
a=0;// 
a=0;//     .line 25
a=0;//     #p0=(Reference,Landroid/support/v7/app/ActionBarImplJB;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public bridge synthetic addOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->addOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic addTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->addTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic addTab(Landroid/support/v7/app/ActionBar$Tab;I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .param p2, "x1"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1, p2}, Landroid/support/v7/app/ActionBarImplICS;->addTab(Landroid/support/v7/app/ActionBar$Tab;I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic addTab(Landroid/support/v7/app/ActionBar$Tab;IZ)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .param p2, "x1"    # I
a=0;//     .param p3, "x2"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1, p2, p3}, Landroid/support/v7/app/ActionBarImplICS;->addTab(Landroid/support/v7/app/ActionBar$Tab;IZ)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic addTab(Landroid/support/v7/app/ActionBar$Tab;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .param p2, "x1"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1, p2}, Landroid/support/v7/app/ActionBarImplICS;->addTab(Landroid/support/v7/app/ActionBar$Tab;Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getCustomView()Landroid/view/View;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getCustomView()Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getDisplayOptions()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getDisplayOptions()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getHeight()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getHeight()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getNavigationItemCount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getNavigationItemCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getNavigationMode()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getNavigationMode()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getSelectedNavigationIndex()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getSelectedNavigationIndex()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getSelectedTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getSelectedTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBar$Tab;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getSubtitle()Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getSubtitle()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getTabAt(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .locals 1
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->getTabAt(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBar$Tab;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getTabCount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getTabCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getThemedContext()Landroid/content/Context;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getThemedContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic getTitle()Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->getTitle()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic hide()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->hide()V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic isShowing()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->isShowing()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic newTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->newTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBar$Tab;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic removeAllTabs()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->removeAllTabs()V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic removeOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->removeOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic removeTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->removeTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic removeTabAt(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->removeTabAt(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic selectTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v7/app/ActionBar$Tab;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->selectTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setCustomView(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setCustomView(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setCustomView(Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setCustomView(Landroid/view/View;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setCustomView(Landroid/view/View;Landroid/support/v7/app/ActionBar$LayoutParams;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/view/View;
a=0;//     .param p2, "x1"    # Landroid/support/v7/app/ActionBar$LayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1, p2}, Landroid/support/v7/app/ActionBarImplICS;->setCustomView(Landroid/view/View;Landroid/support/v7/app/ActionBar$LayoutParams;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayHomeAsUpEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayHomeAsUpEnabled(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayOptions(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayOptions(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayOptions(II)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;//     .param p2, "x1"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1, p2}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayOptions(II)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayShowCustomEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayShowCustomEnabled(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayShowHomeEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayShowHomeEnabled(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayShowTitleEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayShowTitleEnabled(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setDisplayUseLogoEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setDisplayUseLogoEnabled(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setHomeAsUpIndicator(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setHomeAsUpIndicator(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setHomeAsUpIndicator(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setHomeAsUpIndicator(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setHomeButtonEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setHomeButtonEnabled(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setIcon(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setIcon(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setIcon(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setIcon(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setListNavigationCallbacks(Landroid/widget/SpinnerAdapter;Landroid/support/v7/app/ActionBar$OnNavigationListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/widget/SpinnerAdapter;
a=0;//     .param p2, "x1"    # Landroid/support/v7/app/ActionBar$OnNavigationListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1, p2}, Landroid/support/v7/app/ActionBarImplICS;->setListNavigationCallbacks(Landroid/widget/SpinnerAdapter;Landroid/support/v7/app/ActionBar$OnNavigationListener;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setLogo(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setLogo(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setLogo(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setLogo(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setNavigationMode(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setNavigationMode(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setSelectedNavigationItem(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setSelectedNavigationItem(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setSplitBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setSplitBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setStackedBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setStackedBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setSubtitle(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setSubtitle(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setSubtitle(Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setSubtitle(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setTitle(I)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setTitle(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic setTitle(Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0, p1}, Landroid/support/v7/app/ActionBarImplICS;->setTitle(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic show()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplICS;->show()V
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
