package android.support.v7.app; class ActionBarImplHC { void a() { int a;
a=0;// .class Landroid/support/v7/app/ActionBarImplHC;
a=0;// .super Landroid/support/v7/app/ActionBarImplBase;
a=0;// .source "ActionBarImplHC.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v7/app/ActionBarImplHC$CallbackWrapper;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;// .field final mNativeActionModeAwareLayout:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/support/v7/app/ActionBarActivity;Landroid/support/v7/app/ActionBar$Callback;)V
a=0;//     .locals 1
a=0;//     .param p1, "activity"    # Landroid/support/v7/app/ActionBarActivity;
a=0;//     .param p2, "callback"    # Landroid/support/v7/app/ActionBar$Callback;
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     invoke-direct {p0, p1, p2}, Landroid/support/v7/app/ActionBarImplBase;-><init>(Landroid/support/v7/app/ActionBarActivity;Landroid/support/v7/app/ActionBar$Callback;)V
a=0;// 
a=0;//     .line 35
a=0;//     #p0=(Reference,Landroid/support/v7/app/ActionBarImplHC;);
a=0;//     sget v0, Landroid/support/v7/appcompat/R$id;->action_bar_root:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/support/v7/app/ActionBarActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;
a=0;// 
a=0;//     iput-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mNativeActionModeAwareLayout:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;
a=0;// 
a=0;//     .line 39
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mNativeActionModeAwareLayout:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 40
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mNativeActionModeAwareLayout:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;->setActionModeForChildListener(Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;)V
a=0;// 
a=0;//     .line 42
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$002(Landroid/support/v7/app/ActionBarImplHC;Landroid/view/ActionMode;)Landroid/view/ActionMode;
a=0;//     .locals 0
a=0;//     .param p0, "x0"    # Landroid/support/v7/app/ActionBarImplHC;
a=0;//     .param p1, "x1"    # Landroid/view/ActionMode;
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     iput-object p1, p0, Landroid/support/v7/app/ActionBarImplHC;->mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;//     return-object p1
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public hide()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplBase;->hide()V
a=0;// 
a=0;//     .line 61
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ActionMode;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 62
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/ActionMode;->finish()V
a=0;// 
a=0;//     .line 64
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method isShowHideAnimationEnabled()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 69
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ActionMode;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplBase;->isShowHideAnimationEnabled()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     :goto_0
a=0;//     return v0
a=0;// 
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public onActionModeForChild(Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode$Callback;
a=0;//     .locals 1
a=0;//     .param p1, "callback"    # Landroid/view/ActionMode$Callback;
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     new-instance v0, Landroid/support/v7/app/ActionBarImplHC$CallbackWrapper;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v7/app/ActionBarImplHC$CallbackWrapper;);
a=0;//     invoke-direct {v0, p0, p1}, Landroid/support/v7/app/ActionBarImplHC$CallbackWrapper;-><init>(Landroid/support/v7/app/ActionBarImplHC;Landroid/view/ActionMode$Callback;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/app/ActionBarImplHC$CallbackWrapper;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public show()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     invoke-super {p0}, Landroid/support/v7/app/ActionBarImplBase;->show()V
a=0;// 
a=0;//     .line 53
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ActionMode;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 54
a=0;//     iget-object v0, p0, Landroid/support/v7/app/ActionBarImplHC;->mCurActionMode:Landroid/view/ActionMode;
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/ActionMode;->finish()V
a=0;// 
a=0;//     .line 56
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
