package android.support.v7.app; class ActionBar { void a() { int a;
a=0;// .class public abstract Landroid/support/v7/app/ActionBar;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActionBar.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v7/app/ActionBar$Callback;,
a=0;//         Landroid/support/v7/app/ActionBar$LayoutParams;,
a=0;//         Landroid/support/v7/app/ActionBar$TabListener;,
a=0;//         Landroid/support/v7/app/ActionBar$Tab;,
a=0;//         Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;,
a=0;//         Landroid/support/v7/app/ActionBar$OnNavigationListener;,
a=0;//         Landroid/support/v7/app/ActionBar$DisplayOptions;,
a=0;//         Landroid/support/v7/app/ActionBar$NavigationMode;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final DISPLAY_HOME_AS_UP:I = 0x4
a=0;// 
a=0;// .field public static final DISPLAY_SHOW_CUSTOM:I = 0x10
a=0;// 
a=0;// .field public static final DISPLAY_SHOW_HOME:I = 0x2
a=0;// 
a=0;// .field public static final DISPLAY_SHOW_TITLE:I = 0x8
a=0;// 
a=0;// .field public static final DISPLAY_USE_LOGO:I = 0x1
a=0;// 
a=0;// .field public static final NAVIGATION_MODE_LIST:I = 0x1
a=0;// 
a=0;// .field public static final NAVIGATION_MODE_STANDARD:I = 0x0
a=0;// 
a=0;// .field public static final NAVIGATION_MODE_TABS:I = 0x2
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 78
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 1087
a=0;//     #p0=(Reference,Landroid/support/v7/app/ActionBar;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract addOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract addTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract addTab(Landroid/support/v7/app/ActionBar$Tab;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract addTab(Landroid/support/v7/app/ActionBar$Tab;IZ)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract addTab(Landroid/support/v7/app/ActionBar$Tab;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCustomView()Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getDisplayOptions()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getHeight()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getNavigationItemCount()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getNavigationMode()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getSelectedNavigationIndex()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getSelectedTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;//     .annotation build Landroid/support/annotation/Nullable;
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract getSubtitle()Ljava/lang/CharSequence;
a=0;//     .annotation build Landroid/support/annotation/Nullable;
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTabAt(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTabCount()I
a=0;// .end method
a=0;// 
a=0;// .method public getThemedContext()Landroid/content/Context;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 690
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTitle()Ljava/lang/CharSequence;
a=0;//     .annotation build Landroid/support/annotation/Nullable;
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract hide()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract isShowing()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract newTab()Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract removeAllTabs()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract removeOnMenuVisibilityListener(Landroid/support/v7/app/ActionBar$OnMenuVisibilityListener;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract removeTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract removeTabAt(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract selectTab(Landroid/support/v7/app/ActionBar$Tab;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(Landroid/view/View;Landroid/support/v7/app/ActionBar$LayoutParams;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayHomeAsUpEnabled(Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayOptions(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayOptions(II)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayShowCustomEnabled(Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayShowHomeEnabled(Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayShowTitleEnabled(Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDisplayUseLogoEnabled(Z)V
a=0;// .end method
a=0;// 
a=0;// .method public setHomeActionContentDescription(I)V
a=0;//     .locals 0
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 771
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHomeActionContentDescription(Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "description"    # Ljava/lang/CharSequence;
a=0;//         .annotation build Landroid/support/annotation/Nullable;
a=0;//         .end annotation
a=0;//     .end param
a=0;// 
a=0;//     .prologue
a=0;//     .line 751
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHomeAsUpIndicator(I)V
a=0;//     .locals 0
a=0;//     .param p1, "resId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 732
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHomeAsUpIndicator(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "indicator"    # Landroid/graphics/drawable/Drawable;
a=0;//         .annotation build Landroid/support/annotation/Nullable;
a=0;//         .end annotation
a=0;//     .end param
a=0;// 
a=0;//     .prologue
a=0;//     .line 711
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHomeButtonEnabled(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 678
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public abstract setIcon(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setIcon(Landroid/graphics/drawable/Drawable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setListNavigationCallbacks(Landroid/widget/SpinnerAdapter;Landroid/support/v7/app/ActionBar$OnNavigationListener;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setLogo(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setLogo(Landroid/graphics/drawable/Drawable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setNavigationMode(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSelectedNavigationItem(I)V
a=0;// .end method
a=0;// 
a=0;// .method public setSplitBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "d"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 456
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStackedBackgroundDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;//     .locals 0
a=0;//     .param p1, "d"    # Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 445
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubtitle(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubtitle(Ljava/lang/CharSequence;)V
a=0;//     .param p1    # Ljava/lang/CharSequence;
a=0;//         .annotation build Landroid/support/annotation/Nullable;
a=0;//         .end annotation
a=0;//     .end param
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTitle(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTitle(Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract show()V
a=0;// .end method
}}
