package android.support.v7.app; class ActionBar$Tab { void a() { int a;
a=0;// .class public abstract Landroid/support/v7/app/ActionBar$Tab;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActionBar.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v7/app/ActionBar;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x409
a=0;//     name = "Tab"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final INVALID_POSITION:I = -0x1
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 833
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v7/app/ActionBar$Tab;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract getContentDescription()Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCustomView()Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getIcon()Landroid/graphics/drawable/Drawable;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getPosition()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTag()Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getText()Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract select()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setContentDescription(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setContentDescription(Ljava/lang/CharSequence;)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(Landroid/view/View;)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setIcon(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setIcon(Landroid/graphics/drawable/Drawable;)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTabListener(Landroid/support/v7/app/ActionBar$TabListener;)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTag(Ljava/lang/Object;)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setText(I)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setText(Ljava/lang/CharSequence;)Landroid/support/v7/app/ActionBar$Tab;
a=0;// .end method
}}
