package android.support.v7.internal.widget; class NativeActionModeAwareLayout { void a() { int a;
a=0;// .class public Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;
a=0;// .super Landroid/widget/LinearLayout;
a=0;// .source "NativeActionModeAwareLayout.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mActionModeForChildListener:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;//     .locals 0
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "attrs"    # Landroid/util/AttributeSet;
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     invoke-direct {p0, p1, p2}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;// 
a=0;//     .line 34
a=0;//     #p0=(Reference,Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public setActionModeForChildListener(Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "listener"    # Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iput-object p1, p0, Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;->mActionModeForChildListener:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;// 
a=0;//     .line 38
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public startActionModeForChild(Landroid/view/View;Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode;
a=0;//     .locals 1
a=0;//     .param p1, "originalView"    # Landroid/view/View;
a=0;//     .param p2, "callback"    # Landroid/view/ActionMode$Callback;
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;->mActionModeForChildListener:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 43
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/widget/NativeActionModeAwareLayout;->mActionModeForChildListener:Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;
a=0;// 
a=0;//     invoke-interface {v0, p2}, Landroid/support/v7/internal/widget/NativeActionModeAwareLayout$OnActionModeForChildListener;->onActionModeForChild(Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode$Callback;
a=0;// 
a=0;//     move-result-object p2
a=0;// 
a=0;//     .line 45
a=0;//     :cond_0
a=0;//     invoke-super {p0, p1, p2}, Landroid/widget/LinearLayout;->startActionModeForChild(Landroid/view/View;Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
