package android.support.v7.internal.view.menu; class BaseMenuPresenter { void a() { int a;
a=0;// .class public abstract Landroid/support/v7/internal/view/menu/BaseMenuPresenter;
a=0;// .super Ljava/lang/Object;
a=0;// .source "BaseMenuPresenter.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v7/internal/view/menu/MenuPresenter;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mCallback:Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;// .field protected mContext:Landroid/content/Context;
a=0;// 
a=0;// .field private mId:I
a=0;// 
a=0;// .field protected mInflater:Landroid/view/LayoutInflater;
a=0;// 
a=0;// .field private mItemLayoutRes:I
a=0;// 
a=0;// .field protected mMenu:Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;// .field private mMenuLayoutRes:I
a=0;// 
a=0;// .field protected mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;// .field protected mSystemContext:Landroid/content/Context;
a=0;// 
a=0;// .field protected mSystemInflater:Landroid/view/LayoutInflater;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;II)V
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "menuLayoutRes"    # I
a=0;//     .param p3, "itemLayoutRes"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 57
a=0;//     #p0=(Reference,Landroid/support/v7/internal/view/menu/BaseMenuPresenter;);
a=0;//     iput-object p1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mSystemContext:Landroid/content/Context;
a=0;// 
a=0;//     .line 58
a=0;//     invoke-static {p1}, Landroid/view/LayoutInflater;->from(Landroid/content/Context;)Landroid/view/LayoutInflater;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/LayoutInflater;);
a=0;//     iput-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mSystemInflater:Landroid/view/LayoutInflater;
a=0;// 
a=0;//     .line 59
a=0;//     iput p2, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuLayoutRes:I
a=0;// 
a=0;//     .line 60
a=0;//     iput p3, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mItemLayoutRes:I
a=0;// 
a=0;//     .line 61
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected addItemView(Landroid/view/View;I)V
a=0;//     .locals 2
a=0;//     .param p1, "itemView"    # Landroid/view/View;
a=0;//     .param p2, "childIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 130
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getParent()Landroid/view/ViewParent;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ViewParent;);
a=0;//     check-cast v0, Landroid/view/ViewGroup;
a=0;// 
a=0;//     .line 131
a=0;//     .local v0, "currentParent":Landroid/view/ViewGroup;
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 132
a=0;//     invoke-virtual {v0, p1}, Landroid/view/ViewGroup;->removeView(Landroid/view/View;)V
a=0;// 
a=0;//     .line 134
a=0;//     :cond_0
a=0;//     iget-object v1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     #v1=(Reference,Landroid/support/v7/internal/view/menu/MenuView;);
a=0;//     check-cast v1, Landroid/view/ViewGroup;
a=0;// 
a=0;//     invoke-virtual {v1, p1, p2}, Landroid/view/ViewGroup;->addView(Landroid/view/View;I)V
a=0;// 
a=0;//     .line 135
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public abstract bindItemView(Landroid/support/v7/internal/view/menu/MenuItemImpl;Landroid/support/v7/internal/view/menu/MenuView$ItemView;)V
a=0;// .end method
a=0;// 
a=0;// .method public collapseItemActionView(Landroid/support/v7/internal/view/menu/MenuBuilder;Landroid/support/v7/internal/view/menu/MenuItemImpl;)Z
a=0;//     .locals 1
a=0;//     .param p1, "menu"    # Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;//     .param p2, "item"    # Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;// 
a=0;//     .prologue
a=0;//     .line 225
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public createItemView(Landroid/view/ViewGroup;)Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;//     .locals 3
a=0;//     .param p1, "parent"    # Landroid/view/ViewGroup;
a=0;// 
a=0;//     .prologue
a=0;//     .line 159
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mSystemInflater:Landroid/view/LayoutInflater;
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/LayoutInflater;);
a=0;//     iget v1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mItemLayoutRes:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {v0, v1, p1, v2}, Landroid/view/LayoutInflater;->inflate(ILandroid/view/ViewGroup;Z)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public expandItemActionView(Landroid/support/v7/internal/view/menu/MenuBuilder;Landroid/support/v7/internal/view/menu/MenuItemImpl;)Z
a=0;//     .locals 1
a=0;//     .param p1, "menu"    # Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;//     .param p2, "item"    # Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;// 
a=0;//     .prologue
a=0;//     .line 221
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method protected filterLeftoverView(Landroid/view/ViewGroup;I)Z
a=0;//     .locals 1
a=0;//     .param p1, "parent"    # Landroid/view/ViewGroup;
a=0;//     .param p2, "childIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 145
a=0;//     invoke-virtual {p1, p2}, Landroid/view/ViewGroup;->removeViewAt(I)V
a=0;// 
a=0;//     .line 146
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public flagActionItems()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 217
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getId()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 229
a=0;//     iget v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mId:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getItemView(Landroid/support/v7/internal/view/menu/MenuItemImpl;Landroid/view/View;Landroid/view/ViewGroup;)Landroid/view/View;
a=0;//     .locals 2
a=0;//     .param p1, "item"    # Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;//     .param p2, "convertView"    # Landroid/view/View;
a=0;//     .param p3, "parent"    # Landroid/view/ViewGroup;
a=0;// 
a=0;//     .prologue
a=0;//     .line 175
a=0;//     instance-of v1, p2, Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;// 
a=0;//     #v1=(Boolean);
a=0;//     if-eqz v1, :cond_0
a=0;// 
a=0;//     move-object v0, p2
a=0;// 
a=0;//     .line 176
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;// 
a=0;//     .line 180
a=0;//     .local v0, "itemView":Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;//     :goto_0
a=0;//     invoke-virtual {p0, p1, v0}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->bindItemView(Landroid/support/v7/internal/view/menu/MenuItemImpl;Landroid/support/v7/internal/view/menu/MenuView$ItemView;)V
a=0;// 
a=0;//     .line 181
a=0;//     check-cast v0, Landroid/view/View;
a=0;// 
a=0;//     .end local v0    # "itemView":Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;//     return-object v0
a=0;// 
a=0;//     .line 178
a=0;//     :cond_0
a=0;//     #v0=(Uninit);
a=0;//     invoke-virtual {p0, p3}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->createItemView(Landroid/view/ViewGroup;)Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .restart local v0    # "itemView":Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;//     #v0=(Reference,Landroid/support/v7/internal/view/menu/MenuView$ItemView;);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public getMenuView(Landroid/view/ViewGroup;)Landroid/support/v7/internal/view/menu/MenuView;
a=0;//     .locals 3
a=0;//     .param p1, "root"    # Landroid/view/ViewGroup;
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/internal/view/menu/MenuView;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 72
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mSystemInflater:Landroid/view/LayoutInflater;
a=0;// 
a=0;//     iget v1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuLayoutRes:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {v0, v1, p1, v2}, Landroid/view/LayoutInflater;->inflate(ILandroid/view/ViewGroup;Z)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     iput-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     .line 73
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     iget-object v1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenu:Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;//     #v1=(Reference,Landroid/support/v7/internal/view/menu/MenuBuilder;);
a=0;//     invoke-interface {v0, v1}, Landroid/support/v7/internal/view/menu/MenuView;->initialize(Landroid/support/v7/internal/view/menu/MenuBuilder;)V
a=0;// 
a=0;//     .line 74
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     invoke-virtual {p0, v0}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->updateMenuView(Z)V
a=0;// 
a=0;//     .line 77
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/internal/view/menu/MenuView;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public initForMenu(Landroid/content/Context;Landroid/support/v7/internal/view/menu/MenuBuilder;)V
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "menu"    # Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     iput-object p1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mContext:Landroid/content/Context;
a=0;// 
a=0;//     .line 66
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mContext:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v0}, Landroid/view/LayoutInflater;->from(Landroid/content/Context;)Landroid/view/LayoutInflater;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mInflater:Landroid/view/LayoutInflater;
a=0;// 
a=0;//     .line 67
a=0;//     iput-object p2, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenu:Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;//     .line 68
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onCloseMenu(Landroid/support/v7/internal/view/menu/MenuBuilder;Z)V
a=0;//     .locals 1
a=0;//     .param p1, "menu"    # Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;//     .param p2, "allMenusAreClosing"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 204
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mCallback:Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 205
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mCallback:Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;//     invoke-interface {v0, p1, p2}, Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;->onCloseMenu(Landroid/support/v7/internal/view/menu/MenuBuilder;Z)V
a=0;// 
a=0;//     .line 207
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onSubMenuSelected(Landroid/support/v7/internal/view/menu/SubMenuBuilder;)Z
a=0;//     .locals 1
a=0;//     .param p1, "menu"    # Landroid/support/v7/internal/view/menu/SubMenuBuilder;
a=0;// 
a=0;//     .prologue
a=0;//     .line 210
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mCallback:Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 211
a=0;//     iget-object v0, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mCallback:Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;//     invoke-interface {v0, p1}, Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;->onOpenSubMenu(Landroid/support/v7/internal/view/menu/MenuBuilder;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 213
a=0;//     :goto_0
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// 
a=0;//     :cond_0
a=0;//     #v0=(Reference,Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public setCallback(Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;)V
a=0;//     .locals 0
a=0;//     .param p1, "cb"    # Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;//     .prologue
a=0;//     .line 150
a=0;//     iput-object p1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mCallback:Landroid/support/v7/internal/view/menu/MenuPresenter$Callback;
a=0;// 
a=0;//     .line 151
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setId(I)V
a=0;//     .locals 0
a=0;//     .param p1, "id"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 233
a=0;//     iput p1, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mId:I
a=0;// 
a=0;//     .line 234
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public shouldIncludeItem(ILandroid/support/v7/internal/view/menu/MenuItemImpl;)Z
a=0;//     .locals 1
a=0;//     .param p1, "childIndex"    # I
a=0;//     .param p2, "item"    # Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;// 
a=0;//     .prologue
a=0;//     .line 200
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public updateMenuView(Z)V
a=0;//     .locals 10
a=0;//     .param p1, "cleared"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     iget-object v7, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenuView:Landroid/support/v7/internal/view/menu/MenuView;
a=0;// 
a=0;//     #v7=(Reference,Landroid/support/v7/internal/view/menu/MenuView;);
a=0;//     check-cast v7, Landroid/view/ViewGroup;
a=0;// 
a=0;//     .line 85
a=0;//     .local v7, "parent":Landroid/view/ViewGroup;
a=0;//     if-nez v7, :cond_1
a=0;// 
a=0;//     .line 121
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);v5=(Conflicted);v6=(Conflicted);v8=(Conflicted);v9=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 89
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Uninit);v3=(Uninit);v4=(Uninit);v5=(Uninit);v6=(Uninit);v8=(Uninit);v9=(Uninit);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 90
a=0;//     .local v0, "childIndex":I
a=0;//     #v0=(Null);
a=0;//     iget-object v9, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenu:Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;//     #v9=(Reference,Landroid/support/v7/internal/view/menu/MenuBuilder;);
a=0;//     if-eqz v9, :cond_6
a=0;// 
a=0;//     .line 91
a=0;//     iget-object v9, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenu:Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;//     invoke-virtual {v9}, Landroid/support/v7/internal/view/menu/MenuBuilder;->flagActionItems()V
a=0;// 
a=0;//     .line 92
a=0;//     iget-object v9, p0, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->mMenu:Landroid/support/v7/internal/view/menu/MenuBuilder;
a=0;// 
a=0;//     invoke-virtual {v9}, Landroid/support/v7/internal/view/menu/MenuBuilder;->getVisibleItems()Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v8
a=0;// 
a=0;//     .line 93
a=0;//     .local v8, "visibleItems":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Landroid/support/v7/internal/view/menu/MenuItemImpl;>;"
a=0;//     #v8=(Reference,Ljava/util/ArrayList;);
a=0;//     invoke-virtual {v8}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     .line 94
a=0;//     .local v4, "itemCount":I
a=0;//     #v4=(Integer);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .local v2, "i":I
a=0;//     :goto_0
a=0;//     #v0=(Integer);v1=(Conflicted);v2=(Integer);v3=(Conflicted);v5=(Conflicted);v6=(Conflicted);v9=(Conflicted);
a=0;//     if-ge v2, v4, :cond_6
a=0;// 
a=0;//     .line 95
a=0;//     invoke-virtual {v8, v2}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v3, Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;// 
a=0;//     .line 96
a=0;//     .local v3, "item":Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;//     invoke-virtual {p0, v0, v3}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->shouldIncludeItem(ILandroid/support/v7/internal/view/menu/MenuItemImpl;)Z
a=0;// 
a=0;//     move-result v9
a=0;// 
a=0;//     #v9=(Boolean);
a=0;//     if-eqz v9, :cond_4
a=0;// 
a=0;//     .line 97
a=0;//     invoke-virtual {v7, v0}, Landroid/view/ViewGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 98
a=0;//     .local v1, "convertView":Landroid/view/View;
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     instance-of v9, v1, Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;// 
a=0;//     if-eqz v9, :cond_5
a=0;// 
a=0;//     move-object v9, v1
a=0;// 
a=0;//     #v9=(Reference,Landroid/view/View;);
a=0;//     check-cast v9, Landroid/support/v7/internal/view/menu/MenuView$ItemView;
a=0;// 
a=0;//     invoke-interface {v9}, Landroid/support/v7/internal/view/menu/MenuView$ItemView;->getItemData()Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;// 
a=0;//     move-result-object v6
a=0;// 
a=0;//     .line 100
a=0;//     .local v6, "oldItem":Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;//     :goto_1
a=0;//     #v6=(Reference,Landroid/support/v7/internal/view/menu/MenuItemImpl;);v9=(Conflicted);
a=0;//     invoke-virtual {p0, v3, v1, v7}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->getItemView(Landroid/support/v7/internal/view/menu/MenuItemImpl;Landroid/view/View;Landroid/view/ViewGroup;)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     .line 101
a=0;//     .local v5, "itemView":Landroid/view/View;
a=0;//     #v5=(Reference,Landroid/view/View;);
a=0;//     if-eq v3, v6, :cond_2
a=0;// 
a=0;//     .line 103
a=0;//     const/4 v9, 0x0
a=0;// 
a=0;//     #v9=(Null);
a=0;//     invoke-virtual {v5, v9}, Landroid/view/View;->setPressed(Z)V
a=0;// 
a=0;//     .line 107
a=0;//     :cond_2
a=0;//     #v9=(Conflicted);
a=0;//     if-eq v5, v1, :cond_3
a=0;// 
a=0;//     .line 108
a=0;//     invoke-virtual {p0, v5, v0}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->addItemView(Landroid/view/View;I)V
a=0;// 
a=0;//     .line 110
a=0;//     :cond_3
a=0;//     add-int/lit8 v0, v0, 0x1
a=0;// 
a=0;//     .line 94
a=0;//     .end local v1    # "convertView":Landroid/view/View;
a=0;//     .end local v5    # "itemView":Landroid/view/View;
a=0;//     .end local v6    # "oldItem":Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;//     :cond_4
a=0;//     #v1=(Conflicted);v5=(Conflicted);v6=(Conflicted);
a=0;//     add-int/lit8 v2, v2, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 98
a=0;//     .restart local v1    # "convertView":Landroid/view/View;
a=0;//     :cond_5
a=0;//     #v1=(Reference,Landroid/view/View;);v9=(Boolean);
a=0;//     const/4 v6, 0x0
a=0;// 
a=0;//     #v6=(Null);
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 116
a=0;//     .end local v1    # "convertView":Landroid/view/View;
a=0;//     .end local v2    # "i":I
a=0;//     .end local v3    # "item":Landroid/support/v7/internal/view/menu/MenuItemImpl;
a=0;//     .end local v4    # "itemCount":I
a=0;//     .end local v8    # "visibleItems":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Landroid/support/v7/internal/view/menu/MenuItemImpl;>;"
a=0;//     :cond_6
a=0;//     :goto_2
a=0;//     #v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);v6=(Conflicted);v8=(Conflicted);v9=(Conflicted);
a=0;//     invoke-virtual {v7}, Landroid/view/ViewGroup;->getChildCount()I
a=0;// 
a=0;//     move-result v9
a=0;// 
a=0;//     #v9=(Integer);
a=0;//     if-ge v0, v9, :cond_0
a=0;// 
a=0;//     .line 117
a=0;//     invoke-virtual {p0, v7, v0}, Landroid/support/v7/internal/view/menu/BaseMenuPresenter;->filterLeftoverView(Landroid/view/ViewGroup;I)Z
a=0;// 
a=0;//     move-result v9
a=0;// 
a=0;//     #v9=(Boolean);
a=0;//     if-nez v9, :cond_6
a=0;// 
a=0;//     .line 118
a=0;//     add-int/lit8 v0, v0, 0x1
a=0;// 
a=0;//     goto :goto_2
a=0;// .end method
}}
