package android.support.v4.app; class ActivityCompatHoneycomb { void a() { int a;
a=0;// .class Landroid/support/v4/app/ActivityCompatHoneycomb;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActivityCompatHoneycomb.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/app/ActivityCompatHoneycomb;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static dump(Landroid/app/Activity;Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;//     .param p1, "prefix"    # Ljava/lang/String;
a=0;//     .param p2, "fd"    # Ljava/io/FileDescriptor;
a=0;//     .param p3, "writer"    # Ljava/io/PrintWriter;
a=0;//     .param p4, "args"    # [Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     invoke-virtual {p0, p1, p2, p3, p4}, Landroid/app/Activity;->dump(Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static invalidateOptionsMenu(Landroid/app/Activity;)V
a=0;//     .locals 0
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     invoke-virtual {p0}, Landroid/app/Activity;->invalidateOptionsMenu()V
a=0;// 
a=0;//     .line 30
a=0;//     return-void
a=0;// .end method
}}
