package android.support.v4.app; class ActivityCompatJB { void a() { int a;
a=0;// .class Landroid/support/v4/app/ActivityCompatJB;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActivityCompatJB.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/app/ActivityCompatJB;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static finishAffinity(Landroid/app/Activity;)V
a=0;//     .locals 0
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     invoke-virtual {p0}, Landroid/app/Activity;->finishAffinity()V
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static startActivity(Landroid/content/Context;Landroid/content/Intent;Landroid/os/Bundle;)V
a=0;//     .locals 0
a=0;//     .param p0, "context"    # Landroid/content/Context;
a=0;//     .param p1, "intent"    # Landroid/content/Intent;
a=0;//     .param p2, "options"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/content/Context;->startActivity(Landroid/content/Intent;Landroid/os/Bundle;)V
a=0;// 
a=0;//     .line 27
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static startActivityForResult(Landroid/app/Activity;Landroid/content/Intent;ILandroid/os/Bundle;)V
a=0;//     .locals 0
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;//     .param p1, "intent"    # Landroid/content/Intent;
a=0;//     .param p2, "requestCode"    # I
a=0;//     .param p3, "options"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     invoke-virtual {p0, p1, p2, p3}, Landroid/app/Activity;->startActivityForResult(Landroid/content/Intent;ILandroid/os/Bundle;)V
a=0;// 
a=0;//     .line 31
a=0;//     return-void
a=0;// .end method
}}
