package android.support.v4.app; class FragmentTransaction { void a() { int a;
a=0;// .class public abstract Landroid/support/v4/app/FragmentTransaction;
a=0;// .super Ljava/lang/Object;
a=0;// .source "FragmentTransaction.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v4/app/FragmentTransaction$Transit;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final TRANSIT_ENTER_MASK:I = 0x1000
a=0;// 
a=0;// .field public static final TRANSIT_EXIT_MASK:I = 0x2000
a=0;// 
a=0;// .field public static final TRANSIT_FRAGMENT_CLOSE:I = 0x2002
a=0;// 
a=0;// .field public static final TRANSIT_FRAGMENT_FADE:I = 0x1003
a=0;// 
a=0;// .field public static final TRANSIT_FRAGMENT_OPEN:I = 0x1001
a=0;// 
a=0;// .field public static final TRANSIT_NONE:I = 0x0
a=0;// 
a=0;// .field public static final TRANSIT_UNSET:I = -0x1
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 163
a=0;//     #p0=(Reference,Landroid/support/v4/app/FragmentTransaction;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract add(ILandroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract add(ILandroid/support/v4/app/Fragment;Ljava/lang/String;)Landroid/support/v4/app/FragmentTransaction;
a=0;//     .param p3    # Ljava/lang/String;
a=0;//         .annotation build Landroid/support/annotation/Nullable;
a=0;//         .end annotation
a=0;//     .end param
a=0;// .end method
a=0;// 
a=0;// .method public abstract add(Landroid/support/v4/app/Fragment;Ljava/lang/String;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract addToBackStack(Ljava/lang/String;)Landroid/support/v4/app/FragmentTransaction;
a=0;//     .param p1    # Ljava/lang/String;
a=0;//         .annotation build Landroid/support/annotation/Nullable;
a=0;//         .end annotation
a=0;//     .end param
a=0;// .end method
a=0;// 
a=0;// .method public abstract attach(Landroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract commit()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract commitAllowingStateLoss()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract detach(Landroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract disallowAddToBackStack()Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract hide(Landroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract isAddToBackStackAllowed()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isEmpty()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract remove(Landroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract replace(ILandroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract replace(ILandroid/support/v4/app/Fragment;Ljava/lang/String;)Landroid/support/v4/app/FragmentTransaction;
a=0;//     .param p3    # Ljava/lang/String;
a=0;//         .annotation build Landroid/support/annotation/Nullable;
a=0;//         .end annotation
a=0;//     .end param
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBreadCrumbShortTitle(I)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBreadCrumbShortTitle(Ljava/lang/CharSequence;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBreadCrumbTitle(I)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBreadCrumbTitle(Ljava/lang/CharSequence;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomAnimations(II)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomAnimations(IIII)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTransition(I)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTransitionStyle(I)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
a=0;// 
a=0;// .method public abstract show(Landroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// .end method
}}
