package android.support.v4.app; class LoaderManager { void a() { int a;
a=0;// .class public abstract Landroid/support/v4/app/LoaderManager;
a=0;// .super Ljava/lang/Object;
a=0;// .source "LoaderManager.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v4/app/LoaderManager$LoaderCallbacks;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 43
a=0;//     #p0=(Reference,Landroid/support/v4/app/LoaderManager;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static enableDebugLogging(Z)V
a=0;//     .locals 0
a=0;//     .param p0, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 177
a=0;//     sput-boolean p0, Landroid/support/v4/app/LoaderManagerImpl;->DEBUG:Z
a=0;// 
a=0;//     .line 178
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract destroyLoader(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract dump(Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getLoader(I)Landroid/support/v4/content/Loader;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "<D:",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">(I)",
a=0;//             "Landroid/support/v4/content/Loader",
a=0;//             "<TD;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public hasRunningLoaders()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 184
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract initLoader(ILandroid/os/Bundle;Landroid/support/v4/app/LoaderManager$LoaderCallbacks;)Landroid/support/v4/content/Loader;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "<D:",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">(I",
a=0;//             "Landroid/os/Bundle;",
a=0;//             "Landroid/support/v4/app/LoaderManager$LoaderCallbacks",
a=0;//             "<TD;>;)",
a=0;//             "Landroid/support/v4/content/Loader",
a=0;//             "<TD;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract restartLoader(ILandroid/os/Bundle;Landroid/support/v4/app/LoaderManager$LoaderCallbacks;)Landroid/support/v4/content/Loader;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "<D:",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">(I",
a=0;//             "Landroid/os/Bundle;",
a=0;//             "Landroid/support/v4/app/LoaderManager$LoaderCallbacks",
a=0;//             "<TD;>;)",
a=0;//             "Landroid/support/v4/content/Loader",
a=0;//             "<TD;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end method
}}
