package android.support.v4.app; class NavUtilsJB { void a() { int a;
a=0;// .class Landroid/support/v4/app/NavUtilsJB;
a=0;// .super Ljava/lang/Object;
a=0;// .source "NavUtilsJB.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/app/NavUtilsJB;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getParentActivityIntent(Landroid/app/Activity;)Landroid/content/Intent;
a=0;//     .locals 1
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     invoke-virtual {p0}, Landroid/app/Activity;->getParentActivityIntent()Landroid/content/Intent;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Intent;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getParentActivityName(Landroid/content/pm/ActivityInfo;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p0, "info"    # Landroid/content/pm/ActivityInfo;
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iget-object v0, p0, Landroid/content/pm/ActivityInfo;->parentActivityName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static navigateUpTo(Landroid/app/Activity;Landroid/content/Intent;)V
a=0;//     .locals 0
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;//     .param p1, "upIntent"    # Landroid/content/Intent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     invoke-virtual {p0, p1}, Landroid/app/Activity;->navigateUpTo(Landroid/content/Intent;)Z
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static shouldUpRecreateTask(Landroid/app/Activity;Landroid/content/Intent;)Z
a=0;//     .locals 1
a=0;//     .param p0, "activity"    # Landroid/app/Activity;
a=0;//     .param p1, "targetIntent"    # Landroid/content/Intent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     invoke-virtual {p0, p1}, Landroid/app/Activity;->shouldUpRecreateTask(Landroid/content/Intent;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
}}
