package android.support.v4.app; class NotificationCompatSideChannelService$NotificationSideChannelStub { void a() { int a;
a=0;// .class Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;
a=0;// .super Landroid/support/v4/app/INotificationSideChannel$Stub;
a=0;// .source "NotificationCompatSideChannelService.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x2
a=0;//     name = "NotificationSideChannelStub"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>(Landroid/support/v4/app/NotificationCompatSideChannelService;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 76
a=0;//     iput-object p1, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     invoke-direct {p0}, Landroid/support/v4/app/INotificationSideChannel$Stub;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method synthetic constructor <init>(Landroid/support/v4/app/NotificationCompatSideChannelService;Landroid/support/v4/app/NotificationCompatSideChannelService$1;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;//     .param p2, "x1"    # Landroid/support/v4/app/NotificationCompatSideChannelService$1;
a=0;// 
a=0;//     .prologue
a=0;//     .line 76
a=0;//     invoke-direct {p0, p1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;-><init>(Landroid/support/v4/app/NotificationCompatSideChannelService;)V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public cancel(Ljava/lang/String;ILjava/lang/String;)V
a=0;//     .locals 4
a=0;//     .param p1, "packageName"    # Ljava/lang/String;
a=0;//     .param p2, "id"    # I
a=0;//     .param p3, "tag"    # Ljava/lang/String;
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Landroid/os/RemoteException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     iget-object v2, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     #v2=(Reference,Landroid/support/v4/app/NotificationCompatSideChannelService;);
a=0;//     invoke-static {}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->getCallingUid()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-static {v2, v3, p1}, Landroid/support/v4/app/NotificationCompatSideChannelService;->access$100(Landroid/support/v4/app/NotificationCompatSideChannelService;ILjava/lang/String;)V
a=0;// 
a=0;//     .line 92
a=0;//     invoke-static {}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->clearCallingIdentity()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     .line 94
a=0;//     .local v0, "idToken":J
a=0;//     :try_start_0
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     iget-object v2, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     invoke-virtual {v2, p1, p2, p3}, Landroid/support/v4/app/NotificationCompatSideChannelService;->cancel(Ljava/lang/String;ILjava/lang/String;)V
a=0;//     :try_end_0
a=0;//     .catchall {:try_start_0 .. :try_end_0} :catchall_0
a=0;// 
a=0;//     .line 96
a=0;//     invoke-static {v0, v1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->restoreCallingIdentity(J)V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// 
a=0;//     .line 96
a=0;//     :catchall_0
a=0;//     move-exception v2
a=0;// 
a=0;//     invoke-static {v0, v1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->restoreCallingIdentity(J)V
a=0;// 
a=0;//     throw v2
a=0;// .end method
a=0;// 
a=0;// .method public cancelAll(Ljava/lang/String;)V
a=0;//     .locals 4
a=0;//     .param p1, "packageName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 102
a=0;//     iget-object v2, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     #v2=(Reference,Landroid/support/v4/app/NotificationCompatSideChannelService;);
a=0;//     invoke-static {}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->getCallingUid()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-static {v2, v3, p1}, Landroid/support/v4/app/NotificationCompatSideChannelService;->access$100(Landroid/support/v4/app/NotificationCompatSideChannelService;ILjava/lang/String;)V
a=0;// 
a=0;//     .line 103
a=0;//     invoke-static {}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->clearCallingIdentity()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     .line 105
a=0;//     .local v0, "idToken":J
a=0;//     :try_start_0
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     iget-object v2, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     invoke-virtual {v2, p1}, Landroid/support/v4/app/NotificationCompatSideChannelService;->cancelAll(Ljava/lang/String;)V
a=0;//     :try_end_0
a=0;//     .catchall {:try_start_0 .. :try_end_0} :catchall_0
a=0;// 
a=0;//     .line 107
a=0;//     invoke-static {v0, v1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->restoreCallingIdentity(J)V
a=0;// 
a=0;//     .line 109
a=0;//     return-void
a=0;// 
a=0;//     .line 107
a=0;//     :catchall_0
a=0;//     move-exception v2
a=0;// 
a=0;//     invoke-static {v0, v1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->restoreCallingIdentity(J)V
a=0;// 
a=0;//     throw v2
a=0;// .end method
a=0;// 
a=0;// .method public notify(Ljava/lang/String;ILjava/lang/String;Landroid/app/Notification;)V
a=0;//     .locals 4
a=0;//     .param p1, "packageName"    # Ljava/lang/String;
a=0;//     .param p2, "id"    # I
a=0;//     .param p3, "tag"    # Ljava/lang/String;
a=0;//     .param p4, "notification"    # Landroid/app/Notification;
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Landroid/os/RemoteException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     iget-object v2, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     #v2=(Reference,Landroid/support/v4/app/NotificationCompatSideChannelService;);
a=0;//     invoke-static {}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->getCallingUid()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-static {v2, v3, p1}, Landroid/support/v4/app/NotificationCompatSideChannelService;->access$100(Landroid/support/v4/app/NotificationCompatSideChannelService;ILjava/lang/String;)V
a=0;// 
a=0;//     .line 81
a=0;//     invoke-static {}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->clearCallingIdentity()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     .line 83
a=0;//     .local v0, "idToken":J
a=0;//     :try_start_0
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     iget-object v2, p0, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->this$0:Landroid/support/v4/app/NotificationCompatSideChannelService;
a=0;// 
a=0;//     invoke-virtual {v2, p1, p2, p3, p4}, Landroid/support/v4/app/NotificationCompatSideChannelService;->notify(Ljava/lang/String;ILjava/lang/String;Landroid/app/Notification;)V
a=0;//     :try_end_0
a=0;//     .catchall {:try_start_0 .. :try_end_0} :catchall_0
a=0;// 
a=0;//     .line 85
a=0;//     invoke-static {v0, v1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->restoreCallingIdentity(J)V
a=0;// 
a=0;//     .line 87
a=0;//     return-void
a=0;// 
a=0;//     .line 85
a=0;//     :catchall_0
a=0;//     move-exception v2
a=0;// 
a=0;//     invoke-static {v0, v1}, Landroid/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub;->restoreCallingIdentity(J)V
a=0;// 
a=0;//     throw v2
a=0;// .end method
}}
