package android.support.v4.view; class AccessibilityDelegateCompatIcs { void a() { int a;
a=0;// .class Landroid/support/v4/view/AccessibilityDelegateCompatIcs;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityDelegateCompatIcs.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v4/view/AccessibilityDelegateCompatIcs$AccessibilityDelegateBridge;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 30
a=0;//     #p0=(Reference,Landroid/support/v4/view/AccessibilityDelegateCompatIcs;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static dispatchPopulateAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
a=0;//     .locals 1
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/View;
a=0;//     .param p2, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View$AccessibilityDelegate;->dispatchPopulateAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static newAccessibilityDelegateBridge(Landroid/support/v4/view/AccessibilityDelegateCompatIcs$AccessibilityDelegateBridge;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "bridge"    # Landroid/support/v4/view/AccessibilityDelegateCompatIcs$AccessibilityDelegateBridge;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     new-instance v0, Landroid/support/v4/view/AccessibilityDelegateCompatIcs$1;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/view/AccessibilityDelegateCompatIcs$1;);
a=0;//     invoke-direct {v0, p0}, Landroid/support/v4/view/AccessibilityDelegateCompatIcs$1;-><init>(Landroid/support/v4/view/AccessibilityDelegateCompatIcs$AccessibilityDelegateBridge;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/view/AccessibilityDelegateCompatIcs$1;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static newAccessibilityDelegateDefaultImpl()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     new-instance v0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/view/View$AccessibilityDelegate;);
a=0;//     invoke-direct {v0}, Landroid/view/View$AccessibilityDelegate;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View$AccessibilityDelegate;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static onInitializeAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/View;
a=0;//     .param p2, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View$AccessibilityDelegate;->onInitializeAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// 
a=0;//     .line 93
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static onInitializeAccessibilityNodeInfo(Ljava/lang/Object;Landroid/view/View;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/View;
a=0;//     .param p2, "info"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     check-cast p2, Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     .end local p2    # "info":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View$AccessibilityDelegate;->onInitializeAccessibilityNodeInfo(Landroid/view/View;Landroid/view/accessibility/AccessibilityNodeInfo;)V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static onPopulateAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/View;
a=0;//     .param p2, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 102
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View$AccessibilityDelegate;->onPopulateAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// 
a=0;//     .line 103
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static onRequestSendAccessibilityEvent(Ljava/lang/Object;Landroid/view/ViewGroup;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
a=0;//     .locals 1
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/ViewGroup;
a=0;//     .param p2, "child"    # Landroid/view/View;
a=0;//     .param p3, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2, p3}, Landroid/view/View$AccessibilityDelegate;->onRequestSendAccessibilityEvent(Landroid/view/ViewGroup;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static sendAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/View;
a=0;//     .param p2, "eventType"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View$AccessibilityDelegate;->sendAccessibilityEvent(Landroid/view/View;I)V
a=0;// 
a=0;//     .line 113
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static sendAccessibilityEventUnchecked(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p0, "delegate"    # Ljava/lang/Object;
a=0;//     .param p1, "host"    # Landroid/view/View;
a=0;//     .param p2, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 117
a=0;//     check-cast p0, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p0    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View$AccessibilityDelegate;->sendAccessibilityEventUnchecked(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// 
a=0;//     .line 118
a=0;//     return-void
a=0;// .end method
}}
