package android.support.v4.view; class AccessibilityDelegateCompat$AccessibilityDelegateStubImpl { void a() { int a;
a=0;// .class Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateStubImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityDelegateCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/AccessibilityDelegateCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "AccessibilityDelegateStubImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateStubImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public dispatchPopulateAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
a=0;//     .locals 1
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 68
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAccessibilityNodeProvider(Ljava/lang/Object;Landroid/view/View;)Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat;
a=0;//     .locals 1
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 109
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public newAccessiblityDelegateBridge(Landroid/support/v4/view/AccessibilityDelegateCompat;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "listener"    # Landroid/support/v4/view/AccessibilityDelegateCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 62
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public newAccessiblityDelegateDefaultImpl()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public onInitializeAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 75
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onInitializeAccessibilityNodeInfo(Ljava/lang/Object;Landroid/view/View;Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;)V
a=0;//     .locals 0
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "info"    # Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 81
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPopulateAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onRequestSendAccessibilityEvent(Ljava/lang/Object;Landroid/view/ViewGroup;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
a=0;//     .locals 1
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/ViewGroup;
a=0;//     .param p3, "child"    # Landroid/view/View;
a=0;//     .param p4, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public performAccessibilityAction(Ljava/lang/Object;Landroid/view/View;ILandroid/os/Bundle;)Z
a=0;//     .locals 1
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "action"    # I
a=0;//     .param p4, "args"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 115
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public sendAccessibilityEvent(Ljava/lang/Object;Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "eventType"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public sendAccessibilityEventUnchecked(Ljava/lang/Object;Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;//     .param p2, "host"    # Landroid/view/View;
a=0;//     .param p3, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     return-void
a=0;// .end method
}}
