package android.support.v4.view; class GravityCompat$GravityCompatImplBase { void a() { int a;
a=0;// .class Landroid/support/v4/view/GravityCompat$GravityCompatImplBase;
a=0;// .super Ljava/lang/Object;
a=0;// .source "GravityCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/GravityCompat$GravityCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/GravityCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "GravityCompatImplBase"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/GravityCompat$GravityCompatImplBase;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public apply(IIILandroid/graphics/Rect;IILandroid/graphics/Rect;I)V
a=0;//     .locals 0
a=0;//     .param p1, "gravity"    # I
a=0;//     .param p2, "w"    # I
a=0;//     .param p3, "h"    # I
a=0;//     .param p4, "container"    # Landroid/graphics/Rect;
a=0;//     .param p5, "xAdj"    # I
a=0;//     .param p6, "yAdj"    # I
a=0;//     .param p7, "outRect"    # Landroid/graphics/Rect;
a=0;//     .param p8, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     invoke-static/range {p1 .. p7}, Landroid/view/Gravity;->apply(IIILandroid/graphics/Rect;IILandroid/graphics/Rect;)V
a=0;// 
a=0;//     .line 53
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public apply(IIILandroid/graphics/Rect;Landroid/graphics/Rect;I)V
a=0;//     .locals 0
a=0;//     .param p1, "gravity"    # I
a=0;//     .param p2, "w"    # I
a=0;//     .param p3, "h"    # I
a=0;//     .param p4, "container"    # Landroid/graphics/Rect;
a=0;//     .param p5, "outRect"    # Landroid/graphics/Rect;
a=0;//     .param p6, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     invoke-static {p1, p2, p3, p4, p5}, Landroid/view/Gravity;->apply(IIILandroid/graphics/Rect;Landroid/graphics/Rect;)V
a=0;// 
a=0;//     .line 47
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public applyDisplay(ILandroid/graphics/Rect;Landroid/graphics/Rect;I)V
a=0;//     .locals 0
a=0;//     .param p1, "gravity"    # I
a=0;//     .param p2, "display"    # Landroid/graphics/Rect;
a=0;//     .param p3, "inoutObj"    # Landroid/graphics/Rect;
a=0;//     .param p4, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 58
a=0;//     invoke-static {p1, p2, p3}, Landroid/view/Gravity;->applyDisplay(ILandroid/graphics/Rect;Landroid/graphics/Rect;)V
a=0;// 
a=0;//     .line 59
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public getAbsoluteGravity(II)I
a=0;//     .locals 1
a=0;//     .param p1, "gravity"    # I
a=0;//     .param p2, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     const v0, -0x800001
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     and-int/2addr v0, p1
a=0;// 
a=0;//     return v0
a=0;// .end method
}}
