package android.support.v4.view; class KeyEventCompatEclair { void a() { int a;
a=0;// .class Landroid/support/v4/view/KeyEventCompatEclair;
a=0;// .super Ljava/lang/Object;
a=0;// .source "KeyEventCompatEclair.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/KeyEventCompatEclair;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static dispatch(Landroid/view/KeyEvent;Landroid/view/KeyEvent$Callback;Ljava/lang/Object;Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/KeyEvent;
a=0;//     .param p1, "receiver"    # Landroid/view/KeyEvent$Callback;
a=0;//     .param p2, "state"    # Ljava/lang/Object;
a=0;//     .param p3, "target"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     check-cast p2, Landroid/view/KeyEvent$DispatcherState;
a=0;// 
a=0;//     .end local p2    # "state":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1, p2, p3}, Landroid/view/KeyEvent;->dispatch(Landroid/view/KeyEvent$Callback;Landroid/view/KeyEvent$DispatcherState;Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getKeyDispatcherState(Landroid/view/View;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getKeyDispatcherState()Landroid/view/KeyEvent$DispatcherState;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/KeyEvent$DispatcherState;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static isTracking(Landroid/view/KeyEvent;)Z
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/KeyEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     invoke-virtual {p0}, Landroid/view/KeyEvent;->isTracking()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static startTracking(Landroid/view/KeyEvent;)V
a=0;//     .locals 0
a=0;//     .param p0, "event"    # Landroid/view/KeyEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     invoke-virtual {p0}, Landroid/view/KeyEvent;->startTracking()V
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
}}
