package android.support.v4.view; class MarginLayoutParamsCompatJellybeanMr1 { void a() { int a;
a=0;// .class Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MarginLayoutParamsCompatJellybeanMr1.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     invoke-virtual {p0}, Landroid/view/ViewGroup$MarginLayoutParams;->getLayoutDirection()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     invoke-virtual {p0}, Landroid/view/ViewGroup$MarginLayoutParams;->getMarginEnd()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-virtual {p0}, Landroid/view/ViewGroup$MarginLayoutParams;->getMarginStart()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isMarginRelative(Landroid/view/ViewGroup$MarginLayoutParams;)Z
a=0;//     .locals 1
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     invoke-virtual {p0}, Landroid/view/ViewGroup$MarginLayoutParams;->isMarginRelative()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static resolveLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p1, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     invoke-virtual {p0, p1}, Landroid/view/ViewGroup$MarginLayoutParams;->resolveLayoutDirection(I)V
a=0;// 
a=0;//     .line 54
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p1, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     invoke-virtual {p0, p1}, Landroid/view/ViewGroup$MarginLayoutParams;->setLayoutDirection(I)V
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p1, "marginEnd"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     invoke-virtual {p0, p1}, Landroid/view/ViewGroup$MarginLayoutParams;->setMarginEnd(I)V
a=0;// 
a=0;//     .line 37
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p0, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p1, "marginStart"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     invoke-virtual {p0, p1}, Landroid/view/ViewGroup$MarginLayoutParams;->setMarginStart(I)V
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
}}
