package android.support.v4.view; class MarginLayoutParamsCompat$MarginLayoutParamsCompatImplBase { void a() { int a;
a=0;// .class Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImplBase;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MarginLayoutParamsCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/MarginLayoutParamsCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "MarginLayoutParamsCompatImplBase"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImplBase;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 68
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iget v0, p1, Landroid/view/ViewGroup$MarginLayoutParams;->rightMargin:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     iget v0, p1, Landroid/view/ViewGroup$MarginLayoutParams;->leftMargin:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isMarginRelative(Landroid/view/ViewGroup$MarginLayoutParams;)Z
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public resolveLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 74
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "marginEnd"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 58
a=0;//     iput p2, p1, Landroid/view/ViewGroup$MarginLayoutParams;->rightMargin:I
a=0;// 
a=0;//     .line 59
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "marginStart"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     iput p2, p1, Landroid/view/ViewGroup$MarginLayoutParams;->leftMargin:I
a=0;// 
a=0;//     .line 54
a=0;//     return-void
a=0;// .end method
}}
