package android.support.v4.view; class MarginLayoutParamsCompat$MarginLayoutParamsCompatImplJbMr1 { void a() { int a;
a=0;// .class Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImplJbMr1;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MarginLayoutParamsCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/MarginLayoutParamsCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "MarginLayoutParamsCompatImplJbMr1"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 82
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImplJbMr1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 111
a=0;//     invoke-static {p1}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->getLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     invoke-static {p1}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->getMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 86
a=0;//     invoke-static {p1}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->getMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isMarginRelative(Landroid/view/ViewGroup$MarginLayoutParams;)Z
a=0;//     .locals 1
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;// 
a=0;//     .prologue
a=0;//     .line 106
a=0;//     invoke-static {p1}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->isMarginRelative(Landroid/view/ViewGroup$MarginLayoutParams;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public resolveLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 121
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->resolveLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;// 
a=0;//     .line 122
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->setLayoutDirection(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;// 
a=0;//     .line 117
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "marginEnd"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 101
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->setMarginEnd(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;// 
a=0;//     .line 102
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;//     .locals 0
a=0;//     .param p1, "lp"    # Landroid/view/ViewGroup$MarginLayoutParams;
a=0;//     .param p2, "marginStart"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/MarginLayoutParamsCompatJellybeanMr1;->setMarginStart(Landroid/view/ViewGroup$MarginLayoutParams;I)V
a=0;// 
a=0;//     .line 97
a=0;//     return-void
a=0;// .end method
}}
