package android.support.v4.view; class MotionEventCompatEclair { void a() { int a;
a=0;// .class Landroid/support/v4/view/MotionEventCompatEclair;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MotionEventCompatEclair.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/MotionEventCompatEclair;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static findPointerIndex(Landroid/view/MotionEvent;I)I
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/MotionEvent;
a=0;//     .param p1, "pointerId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     invoke-virtual {p0, p1}, Landroid/view/MotionEvent;->findPointerIndex(I)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getPointerCount(Landroid/view/MotionEvent;)I
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/MotionEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     invoke-virtual {p0}, Landroid/view/MotionEvent;->getPointerCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getPointerId(Landroid/view/MotionEvent;I)I
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/MotionEvent;
a=0;//     .param p1, "pointerIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     invoke-virtual {p0, p1}, Landroid/view/MotionEvent;->getPointerId(I)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getX(Landroid/view/MotionEvent;I)F
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/MotionEvent;
a=0;//     .param p1, "pointerIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     invoke-virtual {p0, p1}, Landroid/view/MotionEvent;->getX(I)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getY(Landroid/view/MotionEvent;I)F
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/MotionEvent;
a=0;//     .param p1, "pointerIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     invoke-virtual {p0, p1}, Landroid/view/MotionEvent;->getY(I)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
}}
