package android.support.v4.view; class ScaleGestureDetectorCompatKitKat { void a() { int a;
a=0;// .class Landroid/support/v4/view/ScaleGestureDetectorCompatKitKat;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ScaleGestureDetectorCompatKitKat.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 30
a=0;//     #p0=(Reference,Landroid/support/v4/view/ScaleGestureDetectorCompatKitKat;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static isQuickScaleEnabled(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "scaleGestureDetector"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     check-cast p0, Landroid/view/ScaleGestureDetector;
a=0;// 
a=0;//     .end local p0    # "scaleGestureDetector":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/ScaleGestureDetector;->isQuickScaleEnabled()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static setQuickScaleEnabled(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "scaleGestureDetector"    # Ljava/lang/Object;
a=0;//     .param p1, "enabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     check-cast p0, Landroid/view/ScaleGestureDetector;
a=0;// 
a=0;//     .end local p0    # "scaleGestureDetector":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/ScaleGestureDetector;->setQuickScaleEnabled(Z)V
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
}}
