package android.support.v4.view; class ViewPropertyAnimatorCompatJB { void a() { int a;
a=0;// .class Landroid/support/v4/view/ViewPropertyAnimatorCompatJB;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ViewPropertyAnimatorCompatJB.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/ViewPropertyAnimatorCompatJB;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static withEndAction(Landroid/view/View;Ljava/lang/Runnable;)V
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "runnable"    # Ljava/lang/Runnable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     invoke-virtual {p0}, Landroid/view/View;->animate()Landroid/view/ViewPropertyAnimator;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ViewPropertyAnimator;);
a=0;//     invoke-virtual {v0, p1}, Landroid/view/ViewPropertyAnimator;->withEndAction(Ljava/lang/Runnable;)Landroid/view/ViewPropertyAnimator;
a=0;// 
a=0;//     .line 28
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static withLayer(Landroid/view/View;)V
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     invoke-virtual {p0}, Landroid/view/View;->animate()Landroid/view/ViewPropertyAnimator;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ViewPropertyAnimator;);
a=0;//     invoke-virtual {v0}, Landroid/view/ViewPropertyAnimator;->withLayer()Landroid/view/ViewPropertyAnimator;
a=0;// 
a=0;//     .line 32
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static withStartAction(Landroid/view/View;Ljava/lang/Runnable;)V
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "runnable"    # Ljava/lang/Runnable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     invoke-virtual {p0}, Landroid/view/View;->animate()Landroid/view/ViewPropertyAnimator;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ViewPropertyAnimator;);
a=0;//     invoke-virtual {v0, p1}, Landroid/view/ViewPropertyAnimator;->withStartAction(Ljava/lang/Runnable;)Landroid/view/ViewPropertyAnimator;
a=0;// 
a=0;//     .line 24
a=0;//     return-void
a=0;// .end method
}}
