package android.support.v4.view; class ViewCompatHC { void a() { int a;
a=0;// .class Landroid/support/v4/view/ViewCompatHC;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ViewCompatHC.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/ViewCompatHC;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getAlpha(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getAlpha()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method static getFrameTime()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     invoke-static {}, Landroid/animation/ValueAnimator;->getFrameDelay()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public static getLayerType(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getLayerType()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getMeasuredHeightAndState(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 49
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getMeasuredHeightAndState()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getMeasuredState(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getMeasuredState()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getMeasuredWidthAndState(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getMeasuredWidthAndState()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getPivotX(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 141
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getPivotX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getPivotY(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 145
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getPivotY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getRotation(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 73
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getRotation()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getRotationX(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 77
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getRotationX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getRotationY(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 81
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getRotationY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getScaleX(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 85
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getScaleX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getScaleY(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 89
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getScaleY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getTranslationX(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getTranslationX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getTranslationY(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 61
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getTranslationY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getX(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getY(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 69
a=0;//     invoke-virtual {p0}, Landroid/view/View;->getY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static resolveSizeAndState(III)I
a=0;//     .locals 1
a=0;//     .param p0, "size"    # I
a=0;//     .param p1, "measureSpec"    # I
a=0;//     .param p2, "childMeasuredState"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     invoke-static {p0, p1, p2}, Landroid/view/View;->resolveSizeAndState(III)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static setAlpha(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 101
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setAlpha(F)V
a=0;// 
a=0;//     .line 102
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setLayerType(Landroid/view/View;ILandroid/graphics/Paint;)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "layerType"    # I
a=0;//     .param p2, "paint"    # Landroid/graphics/Paint;
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/view/View;->setLayerType(ILandroid/graphics/Paint;)V
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setPivotX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 133
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setPivotX(F)V
a=0;// 
a=0;//     .line 134
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setPivotY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 137
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setPivotY(F)V
a=0;// 
a=0;//     .line 138
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setRotation(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 113
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setRotation(F)V
a=0;// 
a=0;//     .line 114
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setRotationX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 117
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setRotationX(F)V
a=0;// 
a=0;//     .line 118
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setRotationY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 121
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setRotationY(F)V
a=0;// 
a=0;//     .line 122
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setScaleX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 125
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setScaleX(F)V
a=0;// 
a=0;//     .line 126
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setScaleY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 129
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setScaleY(F)V
a=0;// 
a=0;//     .line 130
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setTranslationX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 93
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setTranslationX(F)V
a=0;// 
a=0;//     .line 94
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setTranslationY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 97
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setTranslationY(F)V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 105
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setX(F)V
a=0;// 
a=0;//     .line 106
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;//     .param p1, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 109
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setY(F)V
a=0;// 
a=0;//     .line 110
a=0;//     return-void
a=0;// .end method
}}
