package android.support.v4.view; class ViewCompatICS { void a() { int a;
a=0;// .class Landroid/support/v4/view/ViewCompatICS;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ViewCompatICS.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/ViewCompatICS;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static canScrollHorizontally(Landroid/view/View;I)Z
a=0;//     .locals 1
a=0;//     .param p0, "v"    # Landroid/view/View;
a=0;//     .param p1, "direction"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->canScrollHorizontally(I)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static canScrollVertically(Landroid/view/View;I)Z
a=0;//     .locals 1
a=0;//     .param p0, "v"    # Landroid/view/View;
a=0;//     .param p1, "direction"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->canScrollVertically(I)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static onInitializeAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p0, "v"    # Landroid/view/View;
a=0;//     .param p1, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->onInitializeAccessibilityEvent(Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// 
a=0;//     .line 47
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static onInitializeAccessibilityNodeInfo(Landroid/view/View;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "v"    # Landroid/view/View;
a=0;//     .param p1, "info"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     check-cast p1, Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     .end local p1    # "info":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->onInitializeAccessibilityNodeInfo(Landroid/view/accessibility/AccessibilityNodeInfo;)V
a=0;// 
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static onPopulateAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p0, "v"    # Landroid/view/View;
a=0;//     .param p1, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->onPopulateAccessibilityEvent(Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// 
a=0;//     .line 43
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setAccessibilityDelegate(Landroid/view/View;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "v"    # Landroid/view/View;
a=0;//     .param p1, "delegate"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     check-cast p1, Landroid/view/View$AccessibilityDelegate;
a=0;// 
a=0;//     .end local p1    # "delegate":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/View;->setAccessibilityDelegate(Landroid/view/View$AccessibilityDelegate;)V
a=0;// 
a=0;//     .line 39
a=0;//     return-void
a=0;// .end method
}}
