package android.support.v4.view; class ViewCompat$ViewCompatImpl { void a() { int a;
a=0;// .class interface abstract Landroid/support/v4/view/ViewCompat$ViewCompatImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ViewCompat.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/ViewCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x608
a=0;//     name = "ViewCompatImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract animate(Landroid/view/View;)Landroid/support/v4/view/ViewPropertyAnimatorCompat;
a=0;// .end method
a=0;// 
a=0;// .method public abstract canScrollHorizontally(Landroid/view/View;I)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract canScrollVertically(Landroid/view/View;I)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract dispatchFinishTemporaryDetach(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract dispatchStartTemporaryDetach(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAccessibilityLiveRegion(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAccessibilityNodeProvider(Landroid/view/View;)Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAlpha(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getImportantForAccessibility(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getLabelFor(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getLayerType(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getLayoutDirection(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMeasuredHeightAndState(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMeasuredState(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMeasuredWidthAndState(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMinimumHeight(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMinimumWidth(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getOverScrollMode(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getPaddingEnd(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getPaddingStart(Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getParentForAccessibility(Landroid/view/View;)Landroid/view/ViewParent;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getPivotX(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getPivotY(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getRotation(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getRotationX(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getRotationY(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getScaleX(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getScaleY(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTranslationX(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTranslationY(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getX(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract getY(Landroid/view/View;)F
a=0;// .end method
a=0;// 
a=0;// .method public abstract hasTransientState(Landroid/view/View;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isOpaque(Landroid/view/View;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract onInitializeAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract onInitializeAccessibilityNodeInfo(Landroid/view/View;Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract onPopulateAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract performAccessibilityAction(Landroid/view/View;ILandroid/os/Bundle;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract postInvalidateOnAnimation(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract postInvalidateOnAnimation(Landroid/view/View;IIII)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract postOnAnimation(Landroid/view/View;Ljava/lang/Runnable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract postOnAnimationDelayed(Landroid/view/View;Ljava/lang/Runnable;J)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract resolveSizeAndState(III)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract setAccessibilityDelegate(Landroid/view/View;Landroid/support/v4/view/AccessibilityDelegateCompat;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setAccessibilityLiveRegion(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setAlpha(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setHasTransientState(Landroid/view/View;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setImportantForAccessibility(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setLabelFor(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setLayerPaint(Landroid/view/View;Landroid/graphics/Paint;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setLayerType(Landroid/view/View;ILandroid/graphics/Paint;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setLayoutDirection(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setOverScrollMode(Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setPaddingRelative(Landroid/view/View;IIII)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setPivotX(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setPivotY(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setRotation(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setRotationX(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setRotationY(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setScaleX(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setScaleY(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTranslationX(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTranslationY(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setX(Landroid/view/View;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setY(Landroid/view/View;F)V
a=0;// .end method
}}
