package android.support.v4.view; class ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl { void a() { int a;
a=0;// .class Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;
a=0;// .super Landroid/support/v4/view/ViewPropertyAnimatorCompat$BaseViewPropertyAnimatorCompatImpl;
a=0;// .source "ViewPropertyAnimatorCompat.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/ViewPropertyAnimatorCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "ICSViewPropertyAnimatorCompatImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 231
a=0;//     invoke-direct {p0}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$BaseViewPropertyAnimatorCompatImpl;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public alpha(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 240
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->alpha(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 241
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public alphaBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 275
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->alphaBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 276
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public cancel(Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 330
a=0;//     invoke-static {p1}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->cancel(Landroid/view/View;)V
a=0;// 
a=0;//     .line 331
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public getDuration(Landroid/view/View;)J
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 255
a=0;//     invoke-static {p1}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->getDuration(Landroid/view/View;)J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getStartDelay(Landroid/view/View;)J
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 270
a=0;//     invoke-static {p1}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->getStartDelay(Landroid/view/View;)J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public rotation(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 280
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->rotation(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 281
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public rotationBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 285
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->rotationBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 286
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public rotationX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 290
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->rotationX(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 291
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public rotationXBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 295
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->rotationXBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 296
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public rotationY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 300
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->rotationY(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 301
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public rotationYBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 305
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->rotationYBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 306
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public scaleX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 310
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->scaleX(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 311
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public scaleXBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 315
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->scaleXBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 316
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public scaleY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 320
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->scaleY(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 321
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public scaleYBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 325
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->scaleYBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 326
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDuration(Landroid/view/View;J)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 235
a=0;//     invoke-static {p1, p2, p3}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->setDuration(Landroid/view/View;J)V
a=0;// 
a=0;//     .line 236
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setInterpolator(Landroid/view/View;Landroid/view/animation/Interpolator;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # Landroid/view/animation/Interpolator;
a=0;// 
a=0;//     .prologue
a=0;//     .line 260
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->setInterpolator(Landroid/view/View;Landroid/view/animation/Interpolator;)V
a=0;// 
a=0;//     .line 261
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setListener(Landroid/view/View;Landroid/support/v4/view/ViewPropertyAnimatorListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "listener"    # Landroid/support/v4/view/ViewPropertyAnimatorListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 370
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->setListener(Landroid/view/View;Landroid/support/v4/view/ViewPropertyAnimatorListener;)V
a=0;// 
a=0;//     .line 371
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStartDelay(Landroid/view/View;J)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 265
a=0;//     invoke-static {p1, p2, p3}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->setStartDelay(Landroid/view/View;J)V
a=0;// 
a=0;//     .line 266
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public start(Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 365
a=0;//     invoke-static {p1}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->start(Landroid/view/View;)V
a=0;// 
a=0;//     .line 366
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public translationX(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 245
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->translationX(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 246
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public translationXBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 355
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->translationXBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 356
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public translationY(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 250
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->translationY(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 251
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public translationYBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 360
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->translationYBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 361
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public withEndAction(Landroid/view/View;Ljava/lang/Runnable;)V
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "runnable"    # Ljava/lang/Runnable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 375
a=0;//     new-instance v0, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$1;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$1;);
a=0;//     invoke-direct {v0, p0, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$1;-><init>(Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;Ljava/lang/Runnable;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$1;);
a=0;//     invoke-virtual {p0, p1, v0}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;->setListener(Landroid/view/View;Landroid/support/v4/view/ViewPropertyAnimatorListener;)V
a=0;// 
a=0;//     .line 390
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public withLayer(Landroid/view/View;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 413
a=0;//     invoke-static {p1}, Landroid/support/v4/view/ViewCompat;->getLayerType(Landroid/view/View;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 414
a=0;//     .local v0, "currentLayerType":I
a=0;//     #v0=(Integer);
a=0;//     new-instance v1, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$3;
a=0;// 
a=0;//     #v1=(UninitRef,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$3;);
a=0;//     invoke-direct {v1, p0, v0}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$3;-><init>(Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;I)V
a=0;// 
a=0;//     #v1=(Reference,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$3;);
a=0;//     invoke-virtual {p0, p1, v1}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;->setListener(Landroid/view/View;Landroid/support/v4/view/ViewPropertyAnimatorListener;)V
a=0;// 
a=0;//     .line 429
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public withStartAction(Landroid/view/View;Ljava/lang/Runnable;)V
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "runnable"    # Ljava/lang/Runnable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 394
a=0;//     new-instance v0, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$2;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$2;);
a=0;//     invoke-direct {v0, p0, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$2;-><init>(Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;Ljava/lang/Runnable;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl$2;);
a=0;//     invoke-virtual {p0, p1, v0}, Landroid/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl;->setListener(Landroid/view/View;Landroid/support/v4/view/ViewPropertyAnimatorListener;)V
a=0;// 
a=0;//     .line 409
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public x(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 335
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->x(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 336
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public xBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 340
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->xBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 341
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public y(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 345
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->y(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 346
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public yBy(Landroid/view/View;F)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "value"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 350
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/view/ViewPropertyAnimatorCompatICS;->yBy(Landroid/view/View;F)V
a=0;// 
a=0;//     .line 351
a=0;//     return-void
a=0;// .end method
}}
