package android.support.v7.view; class ActionMode { void a() { int a;
a=0;// .class public abstract Landroid/support/v7/view/ActionMode;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActionMode.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v7/view/ActionMode$Callback;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mTag:Ljava/lang/Object;
a=0;// 
a=0;// .field private mTitleOptionalHint:Z
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 239
a=0;//     #p0=(Reference,Landroid/support/v7/view/ActionMode;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract finish()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCustomView()Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMenu()Landroid/view/Menu;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMenuInflater()Landroid/view/MenuInflater;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getSubtitle()Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public getTag()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 72
a=0;//     iget-object v0, p0, Landroid/support/v7/view/ActionMode;->mTag:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTitle()Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public getTitleOptionalHint()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     iget-boolean v0, p0, Landroid/support/v7/view/ActionMode;->mTitleOptionalHint:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract invalidate()V
a=0;// .end method
a=0;// 
a=0;// .method public isTitleOptional()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 147
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isUiFocusable()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 216
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubtitle(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubtitle(Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public setTag(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "tag"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     iput-object p1, p0, Landroid/support/v7/view/ActionMode;->mTag:Ljava/lang/Object;
a=0;// 
a=0;//     .line 60
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTitle(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTitle(Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public setTitleOptionalHint(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "titleOptional"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 129
a=0;//     iput-boolean p1, p0, Landroid/support/v7/view/ActionMode;->mTitleOptionalHint:Z
a=0;// 
a=0;//     .line 130
a=0;//     return-void
a=0;// .end method
}}
