package android.support.v4.net; class TrafficStatsCompat$IcsTrafficStatsCompatImpl { void a() { int a;
a=0;// .class Landroid/support/v4/net/TrafficStatsCompat$IcsTrafficStatsCompatImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "TrafficStatsCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/net/TrafficStatsCompat$TrafficStatsCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/net/TrafficStatsCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "IcsTrafficStatsCompatImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/net/TrafficStatsCompat$IcsTrafficStatsCompatImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public clearThreadStatsTag()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     invoke-static {}, Landroid/support/v4/net/TrafficStatsCompatIcs;->clearThreadStatsTag()V
a=0;// 
a=0;//     .line 88
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public getThreadStatsTag()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     invoke-static {}, Landroid/support/v4/net/TrafficStatsCompatIcs;->getThreadStatsTag()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public incrementOperationCount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "operationCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 97
a=0;//     invoke-static {p1}, Landroid/support/v4/net/TrafficStatsCompatIcs;->incrementOperationCount(I)V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public incrementOperationCount(II)V
a=0;//     .locals 0
a=0;//     .param p1, "tag"    # I
a=0;//     .param p2, "operationCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 102
a=0;//     invoke-static {p1, p2}, Landroid/support/v4/net/TrafficStatsCompatIcs;->incrementOperationCount(II)V
a=0;// 
a=0;//     .line 103
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setThreadStatsTag(I)V
a=0;//     .locals 0
a=0;//     .param p1, "tag"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     invoke-static {p1}, Landroid/support/v4/net/TrafficStatsCompatIcs;->setThreadStatsTag(I)V
a=0;// 
a=0;//     .line 108
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public tagSocket(Ljava/net/Socket;)V
a=0;//     .locals 0
a=0;//     .param p1, "socket"    # Ljava/net/Socket;
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Ljava/net/SocketException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     invoke-static {p1}, Landroid/support/v4/net/TrafficStatsCompatIcs;->tagSocket(Ljava/net/Socket;)V
a=0;// 
a=0;//     .line 113
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public untagSocket(Ljava/net/Socket;)V
a=0;//     .locals 0
a=0;//     .param p1, "socket"    # Ljava/net/Socket;
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Ljava/net/SocketException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 117
a=0;//     invoke-static {p1}, Landroid/support/v4/net/TrafficStatsCompatIcs;->untagSocket(Ljava/net/Socket;)V
a=0;// 
a=0;//     .line 118
a=0;//     return-void
a=0;// .end method
}}
