package android.support.v4.print; class PrintHelper$PrintHelperStubImpl { void a() { int a;
a=0;// .class final Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "PrintHelper.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/print/PrintHelper$PrintHelperVersionImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/print/PrintHelper;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x1a
a=0;//     name = "PrintHelperStubImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field mColorMode:I
a=0;// 
a=0;// .field mOrientation:I
a=0;// 
a=0;// .field mScaleMode:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v0, 0x2
a=0;// 
a=0;//     .line 101
a=0;//     #v0=(PosByte);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 102
a=0;//     #p0=(Reference,Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;);
a=0;//     iput v0, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mScaleMode:I
a=0;// 
a=0;//     .line 103
a=0;//     iput v0, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mColorMode:I
a=0;// 
a=0;//     .line 104
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput v0, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mOrientation:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method synthetic constructor <init>(Landroid/support/v4/print/PrintHelper$1;)V
a=0;//     .locals 0
a=0;//     .param p1, "x0"    # Landroid/support/v4/print/PrintHelper$1;
a=0;// 
a=0;//     .prologue
a=0;//     .line 101
a=0;//     invoke-direct {p0}, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getColorMode()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     iget v0, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mColorMode:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrientation()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 124
a=0;//     iget v0, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mOrientation:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getScaleMode()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 128
a=0;//     iget v0, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mScaleMode:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public printBitmap(Ljava/lang/String;Landroid/graphics/Bitmap;)V
a=0;//     .locals 0
a=0;//     .param p1, "jobName"    # Ljava/lang/String;
a=0;//     .param p2, "bitmap"    # Landroid/graphics/Bitmap;
a=0;// 
a=0;//     .prologue
a=0;//     .line 133
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public printBitmap(Ljava/lang/String;Landroid/net/Uri;)V
a=0;//     .locals 0
a=0;//     .param p1, "jobName"    # Ljava/lang/String;
a=0;//     .param p2, "imageFile"    # Landroid/net/Uri;
a=0;// 
a=0;//     .prologue
a=0;//     .line 137
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setColorMode(I)V
a=0;//     .locals 0
a=0;//     .param p1, "colorMode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 117
a=0;//     iput p1, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mColorMode:I
a=0;// 
a=0;//     .line 118
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrientation(I)V
a=0;//     .locals 0
a=0;//     .param p1, "orientation"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 121
a=0;//     iput p1, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mOrientation:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setScaleMode(I)V
a=0;//     .locals 0
a=0;//     .param p1, "scaleMode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     iput p1, p0, Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;->mScaleMode:I
a=0;// 
a=0;//     .line 108
a=0;//     return-void
a=0;// .end method
}}
