package android.support.v4.view.accessibility; class AccessibilityRecordCompat$AccessibilityRecordImpl { void a() { int a;
a=0;// .class interface abstract Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityRecordCompat.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/accessibility/AccessibilityRecordCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x608
a=0;//     name = "AccessibilityRecordImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract getAddedCount(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getBeforeText(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getClassName(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getContentDescription(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCurrentItemIndex(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getFromIndex(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getItemCount(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMaxScrollX(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMaxScrollY(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getParcelableData(Ljava/lang/Object;)Landroid/os/Parcelable;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getRemovedCount(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getScrollX(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getScrollY(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getSource(Ljava/lang/Object;)Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getText(Ljava/lang/Object;)Ljava/util/List;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Object;",
a=0;//             ")",
a=0;//             "Ljava/util/List",
a=0;//             "<",
a=0;//             "Ljava/lang/CharSequence;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract getToIndex(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getWindowId(Ljava/lang/Object;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract isChecked(Ljava/lang/Object;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isEnabled(Ljava/lang/Object;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isFullScreen(Ljava/lang/Object;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isPassword(Ljava/lang/Object;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isScrollable(Ljava/lang/Object;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract obtain()Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract obtain(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract recycle(Ljava/lang/Object;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setAddedCount(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBeforeText(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setChecked(Ljava/lang/Object;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setClassName(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setContentDescription(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCurrentItemIndex(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setEnabled(Ljava/lang/Object;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setFromIndex(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setFullScreen(Ljava/lang/Object;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setItemCount(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setMaxScrollX(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setMaxScrollY(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setParcelableData(Ljava/lang/Object;Landroid/os/Parcelable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setPassword(Ljava/lang/Object;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setRemovedCount(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setScrollX(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setScrollY(Ljava/lang/Object;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setScrollable(Ljava/lang/Object;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSource(Ljava/lang/Object;Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSource(Ljava/lang/Object;Landroid/view/View;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setToIndex(Ljava/lang/Object;I)V
a=0;// .end method
}}
