package android.support.v4.view.accessibility; class AccessibilityEventCompatIcs { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityEventCompatIcs;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityEventCompatIcs.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityEventCompatIcs;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static appendRecord(Landroid/view/accessibility/AccessibilityEvent;Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     check-cast p1, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p1    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityEvent;->appendRecord(Landroid/view/accessibility/AccessibilityRecord;)V
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getRecord(Landroid/view/accessibility/AccessibilityEvent;I)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;//     .param p1, "index"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityEvent;->getRecord(I)Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/accessibility/AccessibilityRecord;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getRecordCount(Landroid/view/accessibility/AccessibilityEvent;)I
a=0;//     .locals 1
a=0;//     .param p0, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityEvent;->getRecordCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
}}
