package android.support.v4.view.accessibility; class AccessibilityNodeInfoCompatKitKat { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatKitKat;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityNodeInfoCompatKitKat.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatKitKat;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getLiveRegion(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "info"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     .end local p0    # "info":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityNodeInfo;->getLiveRegion()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static setLiveRegion(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "info"    # Ljava/lang/Object;
a=0;//     .param p1, "mode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     .end local p0    # "info":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityNodeInfo;->setLiveRegion(I)V
a=0;// 
a=0;//     .line 31
a=0;//     return-void
a=0;// .end method
}}
