package android.support.v4.view.accessibility; class AccessibilityNodeInfoCompatJellybeanMr2 { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatJellybeanMr2;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityNodeInfoCompatJellybeanMr2.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatJellybeanMr2;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getViewIdResourceName(Ljava/lang/Object;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p0, "info"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     .end local p0    # "info":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityNodeInfo;->getViewIdResourceName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static setViewIdResourceName(Ljava/lang/Object;Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p0, "info"    # Ljava/lang/Object;
a=0;//     .param p1, "viewId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     .end local p0    # "info":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityNodeInfo;->setViewIdResourceName(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
}}
