package android.support.v4.view.accessibility; class AccessibilityRecordCompat$AccessibilityRecordStubImpl { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordStubImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityRecordCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/accessibility/AccessibilityRecordCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "AccessibilityRecordStubImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 82
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordStubImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAddedCount(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getBeforeText(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getClassName(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 100
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getContentDescription(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCurrentItemIndex(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFromIndex(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getItemCount(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMaxScrollX(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 120
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMaxScrollY(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 124
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getParcelableData(Ljava/lang/Object;)Landroid/os/Parcelable;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 128
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRemovedCount(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 132
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getScrollX(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 136
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getScrollY(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 140
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSource(Ljava/lang/Object;)Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 144
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getText(Ljava/lang/Object;)Ljava/util/List;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Object;",
a=0;//             ")",
a=0;//             "Ljava/util/List",
a=0;//             "<",
a=0;//             "Ljava/lang/CharSequence;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 148
a=0;//     invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/List;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getToIndex(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 152
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getWindowId(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 156
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isChecked(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 160
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isEnabled(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 164
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isFullScreen(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 168
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isPassword(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 172
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isScrollable(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 176
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public obtain()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public obtain(Ljava/lang/Object;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public recycle(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 181
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAddedCount(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "addedCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 185
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBeforeText(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "beforeText"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 189
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setChecked(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "isChecked"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 193
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setClassName(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "className"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 197
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setContentDescription(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "contentDescription"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 201
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCurrentItemIndex(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "currentItemIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 205
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setEnabled(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "isEnabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 209
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFromIndex(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "fromIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 213
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFullScreen(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "isFullScreen"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 217
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setItemCount(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "itemCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 221
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMaxScrollX(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "maxScrollX"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 225
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMaxScrollY(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "maxScrollY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 229
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setParcelableData(Ljava/lang/Object;Landroid/os/Parcelable;)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "parcelableData"    # Landroid/os/Parcelable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 233
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPassword(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "isPassword"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 237
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRemovedCount(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "removedCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 241
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setScrollX(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "scrollX"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 245
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setScrollY(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "scrollY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 249
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setScrollable(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "scrollable"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 253
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSource(Ljava/lang/Object;Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "source"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 257
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSource(Ljava/lang/Object;Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "root"    # Landroid/view/View;
a=0;//     .param p3, "virtualDescendantId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 261
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setToIndex(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p1, "record"    # Ljava/lang/Object;
a=0;//     .param p2, "toIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 265
a=0;//     return-void
a=0;// .end method
}}
