package android.support.v4.view.accessibility; class AccessibilityManagerCompatIcs { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityManagerCompatIcs.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$AccessibilityStateChangeListenerBridge;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 30
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static addAccessibilityStateChangeListener(Landroid/view/accessibility/AccessibilityManager;Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "manager"    # Landroid/view/accessibility/AccessibilityManager;
a=0;//     .param p1, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     check-cast p1, Landroid/view/accessibility/AccessibilityManager$AccessibilityStateChangeListener;
a=0;// 
a=0;//     .end local p1    # "listener":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityManager;->addAccessibilityStateChangeListener(Landroid/view/accessibility/AccessibilityManager$AccessibilityStateChangeListener;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getEnabledAccessibilityServiceList(Landroid/view/accessibility/AccessibilityManager;I)Ljava/util/List;
a=0;//     .locals 1
a=0;//     .param p0, "manager"    # Landroid/view/accessibility/AccessibilityManager;
a=0;//     .param p1, "feedbackTypeFlags"    # I
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Landroid/view/accessibility/AccessibilityManager;",
a=0;//             "I)",
a=0;//             "Ljava/util/List",
a=0;//             "<",
a=0;//             "Landroid/accessibilityservice/AccessibilityServiceInfo;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 58
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityManager;->getEnabledAccessibilityServiceList(I)Ljava/util/List;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/List;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getInstalledAccessibilityServiceList(Landroid/view/accessibility/AccessibilityManager;)Ljava/util/List;
a=0;//     .locals 1
a=0;//     .param p0, "manager"    # Landroid/view/accessibility/AccessibilityManager;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Landroid/view/accessibility/AccessibilityManager;",
a=0;//             ")",
a=0;//             "Ljava/util/List",
a=0;//             "<",
a=0;//             "Landroid/accessibilityservice/AccessibilityServiceInfo;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityManager;->getInstalledAccessibilityServiceList()Ljava/util/List;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/List;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static isTouchExplorationEnabled(Landroid/view/accessibility/AccessibilityManager;)Z
a=0;//     .locals 1
a=0;//     .param p0, "manager"    # Landroid/view/accessibility/AccessibilityManager;
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityManager;->isTouchExplorationEnabled()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static newAccessibilityStateChangeListener(Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$AccessibilityStateChangeListenerBridge;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "bridge"    # Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$AccessibilityStateChangeListenerBridge;
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     new-instance v0, Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$1;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$1;);
a=0;//     invoke-direct {v0, p0}, Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$1;-><init>(Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$AccessibilityStateChangeListenerBridge;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$1;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static removeAccessibilityStateChangeListener(Landroid/view/accessibility/AccessibilityManager;Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "manager"    # Landroid/view/accessibility/AccessibilityManager;
a=0;//     .param p1, "listener"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     check-cast p1, Landroid/view/accessibility/AccessibilityManager$AccessibilityStateChangeListener;
a=0;// 
a=0;//     .end local p1    # "listener":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityManager;->removeAccessibilityStateChangeListener(Landroid/view/accessibility/AccessibilityManager$AccessibilityStateChangeListener;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
}}
