package android.support.v4.view.accessibility; class AccessibilityRecordCompatIcs { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityRecordCompatIcs;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityRecordCompatIcs.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityRecordCompatIcs;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getAddedCount(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getAddedCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getBeforeText(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getBeforeText()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getClassName(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getClassName()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getContentDescription(Ljava/lang/Object;)Ljava/lang/CharSequence;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getContentDescription()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CharSequence;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getCurrentItemIndex(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getCurrentItemIndex()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getFromIndex(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getFromIndex()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getItemCount(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getItemCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getParcelableData(Ljava/lang/Object;)Landroid/os/Parcelable;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getParcelableData()Landroid/os/Parcelable;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/os/Parcelable;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getRemovedCount(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getRemovedCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getScrollX(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 75
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getScrollX()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getScrollY(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getScrollY()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getSource(Ljava/lang/Object;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getSource()Landroid/view/accessibility/AccessibilityNodeInfo;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/accessibility/AccessibilityNodeInfo;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getText(Ljava/lang/Object;)Ljava/util/List;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Object;",
a=0;//             ")",
a=0;//             "Ljava/util/List",
a=0;//             "<",
a=0;//             "Ljava/lang/CharSequence;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getText()Ljava/util/List;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/List;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getToIndex(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getToIndex()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getWindowId(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 95
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getWindowId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isChecked(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 99
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->isChecked()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isEnabled(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 103
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->isEnabled()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isFullScreen(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->isFullScreen()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isPassword(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 111
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->isPassword()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isScrollable(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 115
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->isScrollable()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static obtain()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     invoke-static {}, Landroid/view/accessibility/AccessibilityRecord;->obtain()Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/accessibility/AccessibilityRecord;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static obtain(Ljava/lang/Object;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-static {p0}, Landroid/view/accessibility/AccessibilityRecord;->obtain(Landroid/view/accessibility/AccessibilityRecord;)Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/accessibility/AccessibilityRecord;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static recycle(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 119
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->recycle()V
a=0;// 
a=0;//     .line 120
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setAddedCount(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "addedCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 123
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setAddedCount(I)V
a=0;// 
a=0;//     .line 124
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setBeforeText(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "beforeText"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 127
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setBeforeText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 128
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setChecked(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "isChecked"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 131
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setChecked(Z)V
a=0;// 
a=0;//     .line 132
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setClassName(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "className"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 135
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setClassName(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 136
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setContentDescription(Ljava/lang/Object;Ljava/lang/CharSequence;)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "contentDescription"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setContentDescription(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 140
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setCurrentItemIndex(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "currentItemIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 143
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setCurrentItemIndex(I)V
a=0;// 
a=0;//     .line 144
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setEnabled(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "isEnabled"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 147
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setEnabled(Z)V
a=0;// 
a=0;//     .line 148
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setFromIndex(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "fromIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 151
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setFromIndex(I)V
a=0;// 
a=0;//     .line 152
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setFullScreen(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "isFullScreen"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 155
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setFullScreen(Z)V
a=0;// 
a=0;//     .line 156
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setItemCount(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "itemCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 159
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setItemCount(I)V
a=0;// 
a=0;//     .line 160
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setParcelableData(Ljava/lang/Object;Landroid/os/Parcelable;)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "parcelableData"    # Landroid/os/Parcelable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 163
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setParcelableData(Landroid/os/Parcelable;)V
a=0;// 
a=0;//     .line 164
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setPassword(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "isPassword"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 167
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setPassword(Z)V
a=0;// 
a=0;//     .line 168
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setRemovedCount(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "removedCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 171
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setRemovedCount(I)V
a=0;// 
a=0;//     .line 172
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setScrollX(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "scrollX"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 175
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setScrollX(I)V
a=0;// 
a=0;//     .line 176
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setScrollY(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "scrollY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 179
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setScrollY(I)V
a=0;// 
a=0;//     .line 180
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setScrollable(Ljava/lang/Object;Z)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "scrollable"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 183
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setScrollable(Z)V
a=0;// 
a=0;//     .line 184
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setSource(Ljava/lang/Object;Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "source"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 187
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setSource(Landroid/view/View;)V
a=0;// 
a=0;//     .line 188
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setToIndex(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "toIndex"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 191
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setToIndex(I)V
a=0;// 
a=0;//     .line 192
a=0;//     return-void
a=0;// .end method
}}
