package android.support.v4.view.accessibility; class AccessibilityRecordCompatIcsMr1 { void a() { int a;
a=0;// .class Landroid/support/v4/view/accessibility/AccessibilityRecordCompatIcsMr1;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AccessibilityRecordCompatIcsMr1.java"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/accessibility/AccessibilityRecordCompatIcsMr1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getMaxScrollX(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getMaxScrollX()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getMaxScrollY(Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0}, Landroid/view/accessibility/AccessibilityRecord;->getMaxScrollY()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static setMaxScrollX(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "maxScrollX"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setMaxScrollX(I)V
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setMaxScrollY(Ljava/lang/Object;I)V
a=0;//     .locals 0
a=0;//     .param p0, "record"    # Ljava/lang/Object;
a=0;//     .param p1, "maxScrollY"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     check-cast p0, Landroid/view/accessibility/AccessibilityRecord;
a=0;// 
a=0;//     .end local p0    # "record":Ljava/lang/Object;
a=0;//     invoke-virtual {p0, p1}, Landroid/view/accessibility/AccessibilityRecord;->setMaxScrollY(I)V
a=0;// 
a=0;//     .line 39
a=0;//     return-void
a=0;// .end method
}}
